-- No-op. This migration previously added tree_items.kind, the
-- document_tree_links table, and the workspace_kind index. The node-direct
-- tree model (see 0008_tree.up.sql and docs/improvements/
-- tree-node-workspace-ownership.md) removes all three: the workspace is the
-- tree root, documents are sources via item_sources (not document_root
-- nodes), and node roles are derived from parent_id rather than a kind column.
--
-- The file is kept (not deleted) so the migration sequence and the dev
-- init checksum tracking stay stable. Dev databases are reset; prod is empty.
