// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlcgen

import (
	"context"
	"time"
)

const getAccountBudgetForUsage = `-- name: GetAccountBudgetForUsage :one
UPDATE accounts
SET storage_used_bytes = storage_used_bytes
WHERE account_id = $1
RETURNING budget_limit_minor, budget_exceeded
`

type GetAccountBudgetForUsageRow struct {
	BudgetLimitMinor int64
	BudgetExceeded   bool
}

func (q *Queries) GetAccountBudgetForUsage(ctx context.Context, accountID string) (GetAccountBudgetForUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountBudgetForUsage, accountID)
	var i GetAccountBudgetForUsageRow
	err := row.Scan(&i.BudgetLimitMinor, &i.BudgetExceeded)
	return i, err
}

const getModelPricing = `-- name: GetModelPricing :one
SELECT model, input_cost_per_mtoken_minor, output_cost_per_mtoken_minor, currency
FROM model_pricing
WHERE model = $1
`

type GetModelPricingRow struct {
	Model                    string
	InputCostPerMtokenMinor  int64
	OutputCostPerMtokenMinor int64
	Currency                 string
}

func (q *Queries) GetModelPricing(ctx context.Context, model string) (GetModelPricingRow, error) {
	row := q.db.QueryRowContext(ctx, getModelPricing, model)
	var i GetModelPricingRow
	err := row.Scan(
		&i.Model,
		&i.InputCostPerMtokenMinor,
		&i.OutputCostPerMtokenMinor,
		&i.Currency,
	)
	return i, err
}

const insertUsageEvent = `-- name: InsertUsageEvent :exec
INSERT INTO usage_events
  (event_id, account_id, workspace_id, job_id, model, input_tokens, output_tokens, cost_minor, currency, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (event_id) DO NOTHING
`

type InsertUsageEventParams struct {
	EventID      string
	AccountID    string
	WorkspaceID  string
	JobID        string
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostMinor    int64
	Currency     string
	CreatedAt    time.Time
}

func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) error {
	_, err := q.db.ExecContext(ctx, insertUsageEvent,
		arg.EventID,
		arg.AccountID,
		arg.WorkspaceID,
		arg.JobID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMinor,
		arg.Currency,
		arg.CreatedAt,
	)
	return err
}

const listDailyUsage = `-- name: ListDailyUsage :many
SELECT usage_date::text, SUM(cost_minor)::bigint AS cost_minor
FROM account_usage_daily
WHERE account_id = $1
  AND ($2::text = '' OR usage_date >= $2::date)
  AND ($3::text = '' OR usage_date <  $3::date)
GROUP BY usage_date
ORDER BY usage_date ASC
`

type ListDailyUsageParams struct {
	AccountID   string
	PeriodStart string
	PeriodEnd   string
}

type ListDailyUsageRow struct {
	UsageDate string
	CostMinor int64
}

func (q *Queries) ListDailyUsage(ctx context.Context, arg ListDailyUsageParams) ([]ListDailyUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyUsage, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyUsageRow
	for rows.Next() {
		var i ListDailyUsageRow
		if err := rows.Scan(&i.UsageDate, &i.CostMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT invoice_id, amount_minor, currency, status,
       hosted_invoice_url, invoice_pdf_url,
       COALESCE(TO_CHAR(period_start AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text AS period_start,
       COALESCE(TO_CHAR(period_end   AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text AS period_end,
       COALESCE(TO_CHAR(paid_at      AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text AS paid_at,
       TO_CHAR(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS created_at
FROM invoices
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListInvoicesParams struct {
	AccountID string
	Limit     int32
}

type ListInvoicesRow struct {
	InvoiceID        string
	AmountMinor      int64
	Currency         string
	Status           string
	HostedInvoiceUrl string
	InvoicePdfUrl    string
	PeriodStart      string
	PeriodEnd        string
	PaidAt           string
	CreatedAt        string
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesRow
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.HostedInvoiceUrl,
			&i.InvoicePdfUrl,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT payment_method_id, brand, last4, exp_month, exp_year, is_default
FROM payment_methods
WHERE account_id = $1
ORDER BY is_default DESC, created_at DESC
`

type ListPaymentMethodsRow struct {
	PaymentMethodID string
	Brand           string
	Last4           string
	ExpMonth        int32
	ExpYear         int32
	IsDefault       bool
}

func (q *Queries) ListPaymentMethods(ctx context.Context, accountID string) ([]ListPaymentMethodsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentMethods, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentMethodsRow
	for rows.Next() {
		var i ListPaymentMethodsRow
		if err := rows.Scan(
			&i.PaymentMethodID,
			&i.Brand,
			&i.Last4,
			&i.ExpMonth,
			&i.ExpYear,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageByModel = `-- name: ListUsageByModel :many
SELECT model,
       SUM(input_tokens)::bigint  AS input_tokens,
       SUM(output_tokens)::bigint AS output_tokens,
       SUM(cost_minor)::bigint    AS cost_minor,
       COUNT(*)::bigint           AS event_count,
       MAX(currency)::text        AS currency
FROM usage_events
WHERE account_id = $1
  AND ($2::text = '' OR created_at >= $2::timestamptz)
  AND ($3::text = '' OR created_at <  $3::timestamptz)
GROUP BY model
ORDER BY cost_minor DESC
`

type ListUsageByModelParams struct {
	AccountID   string
	PeriodStart string
	PeriodEnd   string
}

type ListUsageByModelRow struct {
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostMinor    int64
	EventCount   int64
	Currency     string
}

func (q *Queries) ListUsageByModel(ctx context.Context, arg ListUsageByModelParams) ([]ListUsageByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsageByModel, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageByModelRow
	for rows.Next() {
		var i ListUsageByModelRow
		if err := rows.Scan(
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMinor,
			&i.EventCount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountBudgetExceeded = `-- name: MarkAccountBudgetExceeded :exec
UPDATE accounts SET budget_exceeded = TRUE WHERE account_id = $1
`

func (q *Queries) MarkAccountBudgetExceeded(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, markAccountBudgetExceeded, accountID)
	return err
}

const sumUsageCostByAccount = `-- name: SumUsageCostByAccount :one
SELECT COALESCE(SUM(cost_minor), 0)::bigint
FROM usage_events
WHERE account_id = $1
`

func (q *Queries) SumUsageCostByAccount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumUsageCostByAccount, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAccountBudgetLimit = `-- name: UpdateAccountBudgetLimit :exec
UPDATE accounts
SET budget_limit_minor = $2, budget_exceeded = FALSE, updated_at = $3
WHERE account_id = $1
`

type UpdateAccountBudgetLimitParams struct {
	AccountID        string
	BudgetLimitMinor int64
	UpdatedAt        time.Time
}

func (q *Queries) UpdateAccountBudgetLimit(ctx context.Context, arg UpdateAccountBudgetLimitParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountBudgetLimit, arg.AccountID, arg.BudgetLimitMinor, arg.UpdatedAt)
	return err
}

const upsertAccountUsageDaily = `-- name: UpsertAccountUsageDaily :exec
INSERT INTO account_usage_daily
  (account_id, usage_date, model, input_tokens, output_tokens, cost_minor, event_count, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 1, $7)
ON CONFLICT (account_id, usage_date, model) DO UPDATE SET
  input_tokens = account_usage_daily.input_tokens + EXCLUDED.input_tokens,
  output_tokens = account_usage_daily.output_tokens + EXCLUDED.output_tokens,
  cost_minor = account_usage_daily.cost_minor + EXCLUDED.cost_minor,
  event_count = account_usage_daily.event_count + 1,
  updated_at = EXCLUDED.updated_at
`

type UpsertAccountUsageDailyParams struct {
	AccountID    string
	UsageDate    time.Time
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostMinor    int64
	UpdatedAt    time.Time
}

func (q *Queries) UpsertAccountUsageDaily(ctx context.Context, arg UpsertAccountUsageDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccountUsageDaily,
		arg.AccountID,
		arg.UsageDate,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMinor,
		arg.UpdatedAt,
	)
	return err
}
