// Code generated by scripts/generate-firestore-types.mjs; DO NOT EDIT.
// Source: contracts/firestore/job-status.schema.json

package jobstatus

import "time"

const FirestoreJobStatusJSONSchema = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://synthify.local/contracts/firestore/job-status.schema.json",
  "title": "FirestoreJobStatus",
  "description": "Transient Firestore document for job progress and UI notifications. Postgres/API remain the source of truth.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "jobId",
    "jobType",
    "documentId",
    "workspaceId",
    "treeId",
    "status",
    "currentStage",
    "errorMessage",
    "updatedAt"
  ],
  "properties": {
    "jobId": {
      "type": "string",
      "minLength": 1
    },
    "jobType": {
      "type": "string",
      "minLength": 1
    },
    "documentId": {
      "type": "string",
      "minLength": 1
    },
    "workspaceId": {
      "type": "string",
      "minLength": 1
    },
    "treeId": {
      "type": "string"
    },
    "status": {
      "description": "Worker-authored lifecycle state for the transient Firestore job document. queued/running are in-flight, succeeded/failed are terminal. A succeeded PROCESS_DOCUMENT job that altered the workspace tree must also set treeChanged=true.",
      "type": "string",
      "enum": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ]
    },
    "currentStage": {
      "type": "string"
    },
    "progress": {
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    },
    "message": {
      "type": "string"
    },
    "latestActivity": {
      "description": "A short human-readable line describing what the worker is doing right now (e.g. which tool it just ran). Throttled by the worker and overwritten in place. Optional and best-effort; absence is normal.",
      "type": "string",
      "maxLength": 200
    },
    "errorMessage": {
      "type": "string"
    },
    "suggestedWorkspaceName": {
      "type": "string",
      "minLength": 1,
      "maxLength": 64
    },
    "suggestedWorkspaceNameSource": {
      "type": "string",
      "enum": [
        "brief.topic"
      ]
    },
    "createdAt": {
      "type": "string",
      "format": "date-time"
    },
    "startedAt": {
      "type": "string",
      "format": "date-time"
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "completedAt": {
      "type": "string",
      "format": "date-time"
    },
    "expiresAt": {
      "description": "Firestore Timestamp at which this document becomes eligible for automatic deletion by the TTL policy. Written as a native Firestore Timestamp (not RFC3339) so the platform-side TTL field selector can match it.",
      "type": [
        "object",
        "string",
        "number",
        "null"
      ],
      "x-firestore-timestamp": true
    },
    "treeChanged": {
      "description": "True when a successful PROCESS_DOCUMENT job altered the workspace's knowledge tree (created new root nodes and/or merged the document's knowledge into existing nodes). The tree is a single workspace-owned structure — a document's output can create many nodes or fold into existing ones — so the frontend refetches the workspace tree and diff-reveals new nodes rather than grafting a single subtree. workspaceId on this document identifies which tree to refetch.",
      "type": "boolean"
    },
    "stageSummary": {
      "description": "Ordered list of pipeline stage names that the job traversed. Useful for debug-time inspection without pulling job_logs.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "reason": {
      "description": "Failure classification. Populated on status=failed; absent or empty on other states. Lets the UI switch on a value instead of pattern-matching errorMessage.",
      "type": "string",
      "enum": [
        "vertex_model_not_found",
        "quota_exceeded",
        "agent_error",
        "cancelled",
        "internal"
      ]
    }
  }
}`

type FirestoreJobStatusState string

const (
	FirestoreJobStatusStateQueued FirestoreJobStatusState = "queued"
	FirestoreJobStatusStateRunning FirestoreJobStatusState = "running"
	FirestoreJobStatusStateSucceeded FirestoreJobStatusState = "succeeded"
	FirestoreJobStatusStateFailed FirestoreJobStatusState = "failed"
)

type FirestoreJobStatusSuggestedWorkspaceNameSource string

const (
	FirestoreJobStatusSuggestedWorkspaceNameSourceBriefTopic FirestoreJobStatusSuggestedWorkspaceNameSource = "brief.topic"
)

type FirestoreJobStatusReason string

const (
	FirestoreJobStatusReasonVertexModelNotFound FirestoreJobStatusReason = "vertex_model_not_found"
	FirestoreJobStatusReasonQuotaExceeded FirestoreJobStatusReason = "quota_exceeded"
	FirestoreJobStatusReasonAgentError FirestoreJobStatusReason = "agent_error"
	FirestoreJobStatusReasonCancelled FirestoreJobStatusReason = "cancelled"
	FirestoreJobStatusReasonInternal FirestoreJobStatusReason = "internal"
)

const (
	FirestoreJobStatusFieldJobID = "jobId"
	FirestoreJobStatusFieldJobType = "jobType"
	FirestoreJobStatusFieldDocumentID = "documentId"
	FirestoreJobStatusFieldWorkspaceID = "workspaceId"
	FirestoreJobStatusFieldTreeID = "treeId"
	FirestoreJobStatusFieldStatus = "status"
	FirestoreJobStatusFieldCurrentStage = "currentStage"
	FirestoreJobStatusFieldProgress = "progress"
	FirestoreJobStatusFieldMessage = "message"
	FirestoreJobStatusFieldLatestActivity = "latestActivity"
	FirestoreJobStatusFieldErrorMessage = "errorMessage"
	FirestoreJobStatusFieldSuggestedWorkspaceName = "suggestedWorkspaceName"
	FirestoreJobStatusFieldSuggestedWorkspaceNameSource = "suggestedWorkspaceNameSource"
	FirestoreJobStatusFieldCreatedAt = "createdAt"
	FirestoreJobStatusFieldStartedAt = "startedAt"
	FirestoreJobStatusFieldUpdatedAt = "updatedAt"
	FirestoreJobStatusFieldCompletedAt = "completedAt"
	FirestoreJobStatusFieldExpiresAt = "expiresAt"
	FirestoreJobStatusFieldTreeChanged = "treeChanged"
	FirestoreJobStatusFieldStageSummary = "stageSummary"
	FirestoreJobStatusFieldReason = "reason"
)

type FirestoreJobStatus struct {
	JobID string `firestore:"jobId" json:"jobId"`
	JobType string `firestore:"jobType" json:"jobType"`
	DocumentID string `firestore:"documentId" json:"documentId"`
	WorkspaceID string `firestore:"workspaceId" json:"workspaceId"`
	TreeID string `firestore:"treeId" json:"treeId"`
	Status FirestoreJobStatusState `firestore:"status" json:"status"`
	CurrentStage string `firestore:"currentStage" json:"currentStage"`
	Progress *int `firestore:"progress,omitempty" json:"progress,omitempty"`
	Message *string `firestore:"message,omitempty" json:"message,omitempty"`
	LatestActivity *string `firestore:"latestActivity,omitempty" json:"latestActivity,omitempty"`
	ErrorMessage string `firestore:"errorMessage" json:"errorMessage"`
	SuggestedWorkspaceName *string `firestore:"suggestedWorkspaceName,omitempty" json:"suggestedWorkspaceName,omitempty"`
	SuggestedWorkspaceNameSource *FirestoreJobStatusSuggestedWorkspaceNameSource `firestore:"suggestedWorkspaceNameSource,omitempty" json:"suggestedWorkspaceNameSource,omitempty"`
	CreatedAt *string `firestore:"createdAt,omitempty" json:"createdAt,omitempty"`
	StartedAt *string `firestore:"startedAt,omitempty" json:"startedAt,omitempty"`
	UpdatedAt string `firestore:"updatedAt" json:"updatedAt"`
	CompletedAt *string `firestore:"completedAt,omitempty" json:"completedAt,omitempty"`
	ExpiresAt *time.Time `firestore:"expiresAt,omitempty" json:"expiresAt,omitempty"`
	TreeChanged *bool `firestore:"treeChanged,omitempty" json:"treeChanged,omitempty"`
	StageSummary []string `firestore:"stageSummary,omitempty" json:"stageSummary,omitempty"`
	Reason *FirestoreJobStatusReason `firestore:"reason,omitempty" json:"reason,omitempty"`
}
