// @generated by scripts/generate-firestore-types.mjs
// Source: contracts/firestore/job-status.schema.json

export type FirestoreJobStatus = {
  jobId: string;
  jobType: string;
  documentId: string;
  workspaceId: string;
  treeId: string;
  status: "queued" | "running" | "succeeded" | "failed";
  currentStage: string;
  progress?: number;
  message?: string;
  latestActivity?: string;
  errorMessage?: string;
  suggestedWorkspaceName?: string;
  suggestedWorkspaceNameSource?: "brief.topic";
  createdAt?: string;
  startedAt?: string;
  updatedAt: string;
  completedAt?: string;
  expiresAt?: unknown;
  treeChanged?: boolean;
  stageSummary?: string[];
  reason?: "vertex_model_not_found" | "quota_exceeded" | "agent_error" | "cancelled" | "internal";
};
