// Code generated by scripts/generate-firestore-types.mjs; DO NOT EDIT.
// Source: contracts/firestore/chat-turn.schema.json

package chatstatus

import "time"

const FirestoreChatTurnJSONSchema = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://synthify.local/contracts/firestore/chat-turn.schema.json",
  "title": "FirestoreChatTurn",
  "description": "Transient Firestore document carrying one dialogue turn from the worker to the browser. Lives under users/{uid}/chats/{chatId}/turns/{turnId} so the security rules only compare request.auth.uid against the path; workspace authorization happens in PostChatTurn. Postgres remains the source of truth for anything durable.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "chatId",
    "turnId",
    "workspaceId",
    "paperId",
    "status",
    "content",
    "errorMessage",
    "updatedAt"
  ],
  "properties": {
    "chatId": {
      "type": "string",
      "minLength": 1
    },
    "turnId": {
      "type": "string",
      "minLength": 1
    },
    "workspaceId": {
      "description": "Kept as a field rather than a path segment. The path is user-scoped so the rules need no external lookup, but the turn still belongs to a workspace for context selection and telemetry.",
      "type": "string",
      "minLength": 1
    },
    "paperId": {
      "description": "The paper the dialogue is anchored to.",
      "type": "string",
      "minLength": 1
    },
    "status": {
      "description": "Worker-authored lifecycle state. running is in-flight, succeeded/failed are terminal. There is no queued state: chat is dispatched synchronously to keep the first token fast, so the queueing stage of the job pipeline is never observed here.",
      "type": "string",
      "enum": [
        "running",
        "succeeded",
        "failed"
      ]
    },
    "content": {
      "description": "The answer body: a JSON string holding a paper-in-paper ContentNode[]. Held as an opaque string because ContentNode is a recursive discriminated union that the type generator cannot express; the browser parses and validates it against the vendored TypeScript definition, which is the source of truth for the shape. Always rewritten in full, never appended to: onSnapshot does not guarantee delivery of every intermediate state, so a delta scheme would lose sections when writes coalesce.",
      "type": "string"
    },
    "commands": {
      "description": "Canvas operations the browser may dispatch without asking: a JSON string holding a Command[] restricted to OPEN_NODE, CLOSE_NODE, FOCUS_NODE, PIN_NODE and UNPIN_NODE. Only reversible view operations belong here. Written once when the turn completes rather than per section, so the view does not move while the answer is still being generated.",
      "type": "string"
    },
    "proposals": {
      "description": "Structural changes awaiting the user's Apply: a JSON string holding a Command[] of CREATE_CHILD_NODE, PATCH_NODE, MOVE_NODE, MERGE_PAPERS or UPSERT_PAPERS. The browser renders these as a preview and never dispatches them directly. DELETE_NODE is excluded from the model's tool schema entirely and must never appear in either field.",
      "type": "string"
    },
    "selectedContextIds": {
      "description": "Paper ids actually used as context for this turn, surfaced so the user can see what the answer was grounded in.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "sectionCount": {
      "description": "Number of sections generated so far. A turn is produced one section per model call, and content is rewritten in full after each; this lets the UI show progress without diffing the array.",
      "type": "integer",
      "minimum": 0
    },
    "finishReason": {
      "description": "Why generation stopped. section_cap means the per-turn section limit was reached and the answer was cut short, which is a worker-side decision rather than a model one.",
      "type": "string",
      "enum": [
        "stop",
        "max_tokens",
        "section_cap",
        "safety",
        "recitation",
        "other"
      ]
    },
    "reason": {
      "description": "Failure classification. Populated on status=failed; absent or empty otherwise. Mirrors the job-status enum so the UI can switch on a value instead of matching on errorMessage.",
      "type": "string",
      "enum": [
        "vertex_model_not_found",
        "quota_exceeded",
        "agent_error",
        "cancelled",
        "internal"
      ]
    },
    "errorMessage": {
      "type": "string"
    },
    "promptTokens": {
      "description": "Accumulated across every section call in this turn, not just the last one.",
      "type": "integer",
      "minimum": 0
    },
    "completionTokens": {
      "description": "Accumulated across every section call in this turn, not just the last one.",
      "type": "integer",
      "minimum": 0
    },
    "createdAt": {
      "type": "string",
      "format": "date-time"
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "completedAt": {
      "type": "string",
      "format": "date-time"
    },
    "expiresAt": {
      "description": "Firestore Timestamp at which this turn becomes eligible for deletion by the TTL policy. Written as a native Firestore Timestamp (not RFC3339) so the platform-side TTL field selector can match it. Set only on terminal states; a running turn carries no expiry. Bound to a separate google_firestore_field on the turns collection group, since the existing one pins collection=jobs.",
      "type": [
        "object",
        "string",
        "number",
        "null"
      ],
      "x-firestore-timestamp": true
    }
  }
}`

type FirestoreChatTurnState string

const (
	FirestoreChatTurnStateRunning   FirestoreChatTurnState = "running"
	FirestoreChatTurnStateSucceeded FirestoreChatTurnState = "succeeded"
	FirestoreChatTurnStateFailed    FirestoreChatTurnState = "failed"
)

type FirestoreChatTurnFinishReason string

const (
	FirestoreChatTurnFinishReasonStop       FirestoreChatTurnFinishReason = "stop"
	FirestoreChatTurnFinishReasonMaxTokens  FirestoreChatTurnFinishReason = "max_tokens"
	FirestoreChatTurnFinishReasonSectionCap FirestoreChatTurnFinishReason = "section_cap"
	FirestoreChatTurnFinishReasonSafety     FirestoreChatTurnFinishReason = "safety"
	FirestoreChatTurnFinishReasonRecitation FirestoreChatTurnFinishReason = "recitation"
	FirestoreChatTurnFinishReasonOther      FirestoreChatTurnFinishReason = "other"
)

type FirestoreChatTurnReason string

const (
	FirestoreChatTurnReasonVertexModelNotFound FirestoreChatTurnReason = "vertex_model_not_found"
	FirestoreChatTurnReasonQuotaExceeded       FirestoreChatTurnReason = "quota_exceeded"
	FirestoreChatTurnReasonAgentError          FirestoreChatTurnReason = "agent_error"
	FirestoreChatTurnReasonCancelled           FirestoreChatTurnReason = "cancelled"
	FirestoreChatTurnReasonInternal            FirestoreChatTurnReason = "internal"
)

const (
	FirestoreChatTurnFieldChatID             = "chatId"
	FirestoreChatTurnFieldTurnID             = "turnId"
	FirestoreChatTurnFieldWorkspaceID        = "workspaceId"
	FirestoreChatTurnFieldPaperID            = "paperId"
	FirestoreChatTurnFieldStatus             = "status"
	FirestoreChatTurnFieldContent            = "content"
	FirestoreChatTurnFieldCommands           = "commands"
	FirestoreChatTurnFieldProposals          = "proposals"
	FirestoreChatTurnFieldSelectedContextIDs = "selectedContextIds"
	FirestoreChatTurnFieldSectionCount       = "sectionCount"
	FirestoreChatTurnFieldFinishReason       = "finishReason"
	FirestoreChatTurnFieldReason             = "reason"
	FirestoreChatTurnFieldErrorMessage       = "errorMessage"
	FirestoreChatTurnFieldPromptTokens       = "promptTokens"
	FirestoreChatTurnFieldCompletionTokens   = "completionTokens"
	FirestoreChatTurnFieldCreatedAt          = "createdAt"
	FirestoreChatTurnFieldUpdatedAt          = "updatedAt"
	FirestoreChatTurnFieldCompletedAt        = "completedAt"
	FirestoreChatTurnFieldExpiresAt          = "expiresAt"
)

type FirestoreChatTurn struct {
	ChatID             string                         `firestore:"chatId" json:"chatId"`
	TurnID             string                         `firestore:"turnId" json:"turnId"`
	WorkspaceID        string                         `firestore:"workspaceId" json:"workspaceId"`
	PaperID            string                         `firestore:"paperId" json:"paperId"`
	Status             FirestoreChatTurnState         `firestore:"status" json:"status"`
	Content            string                         `firestore:"content" json:"content"`
	Commands           *string                        `firestore:"commands,omitempty" json:"commands,omitempty"`
	Proposals          *string                        `firestore:"proposals,omitempty" json:"proposals,omitempty"`
	SelectedContextIDs []string                       `firestore:"selectedContextIds,omitempty" json:"selectedContextIds,omitempty"`
	SectionCount       *int                           `firestore:"sectionCount,omitempty" json:"sectionCount,omitempty"`
	FinishReason       *FirestoreChatTurnFinishReason `firestore:"finishReason,omitempty" json:"finishReason,omitempty"`
	Reason             *FirestoreChatTurnReason       `firestore:"reason,omitempty" json:"reason,omitempty"`
	ErrorMessage       string                         `firestore:"errorMessage" json:"errorMessage"`
	PromptTokens       *int                           `firestore:"promptTokens,omitempty" json:"promptTokens,omitempty"`
	CompletionTokens   *int                           `firestore:"completionTokens,omitempty" json:"completionTokens,omitempty"`
	CreatedAt          *string                        `firestore:"createdAt,omitempty" json:"createdAt,omitempty"`
	UpdatedAt          string                         `firestore:"updatedAt" json:"updatedAt"`
	CompletedAt        *string                        `firestore:"completedAt,omitempty" json:"completedAt,omitempty"`
	ExpiresAt          *time.Time                     `firestore:"expiresAt,omitempty" json:"expiresAt,omitempty"`
}
