// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: documents.sql

package sqlcgen

import (
	"context"
	"time"
)

const completeDocumentProcessing = `-- name: CompleteDocumentProcessing :execrows
UPDATE documents
SET status = 'completed', extraction_depth = $2, current_stage = '', node_count = $3, updated_at = $4
WHERE document_id = $1
`

type CompleteDocumentProcessingParams struct {
	DocumentID      string
	ExtractionDepth string
	NodeCount       int32
	UpdatedAt       time.Time
}

func (q *Queries) CompleteDocumentProcessing(ctx context.Context, arg CompleteDocumentProcessingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeDocumentProcessing,
		arg.DocumentID,
		arg.ExtractionDepth,
		arg.NodeCount,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countNodesByDocument = `-- name: CountNodesByDocument :one
SELECT COUNT(*)
FROM nodes
WHERE document_id = $1
`

func (q *Queries) CountNodesByDocument(ctx context.Context, documentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodesByDocument, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents (document_id, workspace_id, uploaded_by, filename, mime_type, file_size, status, extraction_depth, node_count, current_stage, error_message, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateDocumentParams struct {
	DocumentID      string
	WorkspaceID     string
	UploadedBy      string
	Filename        string
	MimeType        string
	FileSize        int64
	Status          string
	ExtractionDepth string
	NodeCount       int32
	CurrentStage    string
	ErrorMessage    string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, createDocument,
		arg.DocumentID,
		arg.WorkspaceID,
		arg.UploadedBy,
		arg.Filename,
		arg.MimeType,
		arg.FileSize,
		arg.Status,
		arg.ExtractionDepth,
		arg.NodeCount,
		arg.CurrentStage,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT document_id, workspace_id, uploaded_by, filename, mime_type, file_size, status, extraction_depth, node_count, current_stage, error_message, created_at, updated_at
FROM documents
WHERE document_id = $1
`

func (q *Queries) GetDocument(ctx context.Context, documentID string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, documentID)
	var i Document
	err := row.Scan(
		&i.DocumentID,
		&i.WorkspaceID,
		&i.UploadedBy,
		&i.Filename,
		&i.MimeType,
		&i.FileSize,
		&i.Status,
		&i.ExtractionDepth,
		&i.NodeCount,
		&i.CurrentStage,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT document_id, workspace_id, uploaded_by, filename, mime_type, file_size, status, extraction_depth, node_count, current_stage, error_message, created_at, updated_at
FROM documents
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocuments(ctx context.Context, workspaceID string) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.DocumentID,
			&i.WorkspaceID,
			&i.UploadedBy,
			&i.Filename,
			&i.MimeType,
			&i.FileSize,
			&i.Status,
			&i.ExtractionDepth,
			&i.NodeCount,
			&i.CurrentStage,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentTimestamp = `-- name: UpdateDocumentTimestamp :exec
UPDATE documents
SET updated_at = $2
WHERE document_id = $1
`

type UpdateDocumentTimestampParams struct {
	DocumentID string
	UpdatedAt  time.Time
}

func (q *Queries) UpdateDocumentTimestamp(ctx context.Context, arg UpdateDocumentTimestampParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentTimestamp, arg.DocumentID, arg.UpdatedAt)
	return err
}
