// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: graph.sql

package sqlcgen

import (
	"context"
	"time"
)

const createEdge = `-- name: CreateEdge :exec
INSERT INTO edges (edge_id, document_id, source_node_id, target_node_id, edge_type, description, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateEdgeParams struct {
	EdgeID       string
	DocumentID   string
	SourceNodeID string
	TargetNodeID string
	EdgeType     string
	Description  string
	CreatedAt    time.Time
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) error {
	_, err := q.db.ExecContext(ctx, createEdge,
		arg.EdgeID,
		arg.DocumentID,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.EdgeType,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (node_id, document_id, label, level, category, entity_type, description, summary_html, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateNodeParams struct {
	NodeID      string
	DocumentID  string
	Label       string
	Level       int32
	Category    string
	EntityType  string
	Description string
	SummaryHtml string
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode,
		arg.NodeID,
		arg.DocumentID,
		arg.Label,
		arg.Level,
		arg.Category,
		arg.EntityType,
		arg.Description,
		arg.SummaryHtml,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const getNode = `-- name: GetNode :one
SELECT node_id, document_id, label, level, category, entity_type, description, summary_html, created_by, created_at
FROM nodes
WHERE node_id = $1
`

func (q *Queries) GetNode(ctx context.Context, nodeID string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, nodeID)
	var i Node
	err := row.Scan(
		&i.NodeID,
		&i.DocumentID,
		&i.Label,
		&i.Level,
		&i.Category,
		&i.EntityType,
		&i.Description,
		&i.SummaryHtml,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMemberEmail = `-- name: GetWorkspaceMemberEmail :one
SELECT email
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberEmailParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) GetWorkspaceMemberEmail(ctx context.Context, arg GetWorkspaceMemberEmailParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceMemberEmail, arg.WorkspaceID, arg.UserID)
	var email string
	err := row.Scan(&email)
	return email, err
}

const insertNodeView = `-- name: InsertNodeView :exec
INSERT INTO node_views (workspace_id, user_id, node_id, document_id, viewed_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertNodeViewParams struct {
	WorkspaceID string
	UserID      string
	NodeID      string
	DocumentID  string
	ViewedAt    time.Time
}

func (q *Queries) InsertNodeView(ctx context.Context, arg InsertNodeViewParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeView,
		arg.WorkspaceID,
		arg.UserID,
		arg.NodeID,
		arg.DocumentID,
		arg.ViewedAt,
	)
	return err
}

const listCreatedNodes = `-- name: ListCreatedNodes :many
SELECT node_id, document_id, label, created_at
FROM nodes
WHERE created_by = $1
  AND ($2::text = '' OR document_id = $2::text)
ORDER BY created_at DESC
LIMIT $3
`

type ListCreatedNodesParams struct {
	CreatedBy        string
	DocumentIDFilter string
	RowLimit         int32
}

type ListCreatedNodesRow struct {
	NodeID     string
	DocumentID string
	Label      string
	CreatedAt  time.Time
}

func (q *Queries) ListCreatedNodes(ctx context.Context, arg ListCreatedNodesParams) ([]ListCreatedNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCreatedNodes, arg.CreatedBy, arg.DocumentIDFilter, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreatedNodesRow
	for rows.Next() {
		var i ListCreatedNodesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.DocumentID,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesByDocument = `-- name: ListEdgesByDocument :many
SELECT edge_id, document_id, source_node_id, target_node_id, edge_type, description, created_at
FROM edges
WHERE document_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEdgesByDocument(ctx context.Context, documentID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.EdgeID,
			&i.DocumentID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.EdgeType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeEdges = `-- name: ListNodeEdges :many
SELECT edge_id, document_id, source_node_id, target_node_id, edge_type, description, created_at
FROM edges
WHERE source_node_id = $1 OR target_node_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListNodeEdges(ctx context.Context, sourceNodeID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, listNodeEdges, sourceNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.EdgeID,
			&i.DocumentID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.EdgeType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByDocument = `-- name: ListNodesByDocument :many
SELECT node_id, document_id, label, level, category, entity_type, description, summary_html, created_by, created_at
FROM nodes
WHERE document_id = $1
ORDER BY level ASC, created_at ASC
`

func (q *Queries) ListNodesByDocument(ctx context.Context, documentID string) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.NodeID,
			&i.DocumentID,
			&i.Label,
			&i.Level,
			&i.Category,
			&i.EntityType,
			&i.Description,
			&i.SummaryHtml,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewedNodes = `-- name: ListViewedNodes :many
SELECT nv.node_id, nv.document_id, COALESCE(n.label, nv.node_id) AS label, MAX(nv.viewed_at)::timestamptz AS last_viewed_at, COUNT(*) AS view_count
FROM node_views nv
LEFT JOIN nodes n ON n.node_id = nv.node_id
WHERE nv.workspace_id = $1
  AND nv.user_id = $2
  AND ($3::text = '' OR nv.document_id = $3::text)
GROUP BY nv.node_id, nv.document_id, label
ORDER BY last_viewed_at DESC
LIMIT $4
`

type ListViewedNodesParams struct {
	WorkspaceID      string
	UserID           string
	DocumentIDFilter string
	RowLimit         int32
}

type ListViewedNodesRow struct {
	NodeID       string
	DocumentID   string
	Label        string
	LastViewedAt time.Time
	ViewCount    int64
}

func (q *Queries) ListViewedNodes(ctx context.Context, arg ListViewedNodesParams) ([]ListViewedNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listViewedNodes,
		arg.WorkspaceID,
		arg.UserID,
		arg.DocumentIDFilter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListViewedNodesRow
	for rows.Next() {
		var i ListViewedNodesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.DocumentID,
			&i.Label,
			&i.LastViewedAt,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApprovedAlias = `-- name: UpsertApprovedAlias :exec
INSERT INTO node_aliases (workspace_id, canonical_node_id, alias_node_id, status, updated_at)
VALUES ($1, $2, $3, 'approved', $4)
ON CONFLICT (workspace_id, canonical_node_id, alias_node_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = EXCLUDED.updated_at
`

type UpsertApprovedAliasParams struct {
	WorkspaceID     string
	CanonicalNodeID string
	AliasNodeID     string
	UpdatedAt       time.Time
}

func (q *Queries) UpsertApprovedAlias(ctx context.Context, arg UpsertApprovedAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertApprovedAlias,
		arg.WorkspaceID,
		arg.CanonicalNodeID,
		arg.AliasNodeID,
		arg.UpdatedAt,
	)
	return err
}

const upsertRejectedAlias = `-- name: UpsertRejectedAlias :exec
INSERT INTO node_aliases (workspace_id, canonical_node_id, alias_node_id, status, updated_at)
VALUES ($1, $2, $3, 'rejected', $4)
ON CONFLICT (workspace_id, canonical_node_id, alias_node_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = EXCLUDED.updated_at
`

type UpsertRejectedAliasParams struct {
	WorkspaceID     string
	CanonicalNodeID string
	AliasNodeID     string
	UpdatedAt       time.Time
}

func (q *Queries) UpsertRejectedAlias(ctx context.Context, arg UpsertRejectedAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertRejectedAlias,
		arg.WorkspaceID,
		arg.CanonicalNodeID,
		arg.AliasNodeID,
		arg.UpdatedAt,
	)
	return err
}
