// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"time"
)

type Document struct {
	DocumentID      string
	WorkspaceID     string
	UploadedBy      string
	Filename        string
	MimeType        string
	FileSize        int64
	Status          string
	ExtractionDepth string
	NodeCount       int32
	CurrentStage    string
	ErrorMessage    string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Edge struct {
	EdgeID       string
	DocumentID   string
	SourceNodeID string
	TargetNodeID string
	EdgeType     string
	Description  string
	CreatedAt    time.Time
}

type Node struct {
	NodeID      string
	DocumentID  string
	Label       string
	Level       int32
	Category    string
	EntityType  string
	Description string
	SummaryHtml string
	CreatedBy   string
	CreatedAt   time.Time
}

type NodeAlias struct {
	WorkspaceID     string
	CanonicalNodeID string
	AliasNodeID     string
	Status          string
	UpdatedAt       time.Time
}

type NodeView struct {
	ID          int64
	WorkspaceID string
	UserID      string
	NodeID      string
	DocumentID  string
	ViewedAt    time.Time
}

type Workspace struct {
	WorkspaceID       string
	Name              string
	OwnerID           string
	Plan              string
	StorageUsedBytes  int64
	StorageQuotaBytes int64
	MaxFileSizeBytes  int64
	MaxUploadsPerDay  int64
	CreatedAt         time.Time
}

type WorkspaceMember struct {
	WorkspaceID string
	UserID      string
	Email       string
	Role        string
	IsDev       bool
	InvitedAt   time.Time
	InvitedBy   string
}
