// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workspaces.sql

package sqlcgen

import (
	"context"
	"time"
)

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (workspace_id, name, owner_id, plan, storage_used_bytes, storage_quota_bytes, max_file_size_bytes, max_uploads_per_day, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateWorkspaceParams struct {
	WorkspaceID       string
	Name              string
	OwnerID           string
	Plan              string
	StorageUsedBytes  int64
	StorageQuotaBytes int64
	MaxFileSizeBytes  int64
	MaxUploadsPerDay  int64
	CreatedAt         time.Time
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.WorkspaceID,
		arg.Name,
		arg.OwnerID,
		arg.Plan,
		arg.StorageUsedBytes,
		arg.StorageQuotaBytes,
		arg.MaxFileSizeBytes,
		arg.MaxUploadsPerDay,
		arg.CreatedAt,
	)
	return err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, email, role, is_dev, invited_at, invited_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID string
	UserID      string
	Email       string
	Role        string
	IsDev       bool
	InvitedAt   time.Time
	InvitedBy   string
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Email,
		arg.Role,
		arg.IsDev,
		arg.InvitedAt,
		arg.InvitedBy,
	)
	return err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :execrows
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const demoteWorkspaceOwner = `-- name: DemoteWorkspaceOwner :exec
UPDATE workspace_members
SET role = 'editor'
WHERE workspace_id = $1 AND user_id = $2
`

type DemoteWorkspaceOwnerParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) DemoteWorkspaceOwner(ctx context.Context, arg DemoteWorkspaceOwnerParams) error {
	_, err := q.db.ExecContext(ctx, demoteWorkspaceOwner, arg.WorkspaceID, arg.UserID)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT workspace_id, name, owner_id, plan, storage_used_bytes, storage_quota_bytes, max_file_size_bytes, max_uploads_per_day, created_at
FROM workspaces
WHERE workspace_id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, workspaceID string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, workspaceID)
	var i Workspace
	err := row.Scan(
		&i.WorkspaceID,
		&i.Name,
		&i.OwnerID,
		&i.Plan,
		&i.StorageUsedBytes,
		&i.StorageQuotaBytes,
		&i.MaxFileSizeBytes,
		&i.MaxUploadsPerDay,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT user_id, email, role, is_dev, invited_at, invited_by
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID string
	UserID      string
}

type GetWorkspaceMemberRow struct {
	UserID    string
	Email     string
	Role      string
	IsDev     bool
	InvitedAt time.Time
	InvitedBy string
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMemberRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.IsDev,
		&i.InvitedAt,
		&i.InvitedBy,
	)
	return i, err
}

const getWorkspaceOwnerID = `-- name: GetWorkspaceOwnerID :one
SELECT owner_id
FROM workspaces
WHERE workspace_id = $1
`

func (q *Queries) GetWorkspaceOwnerID(ctx context.Context, workspaceID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceOwnerID, workspaceID)
	var owner_id string
	err := row.Scan(&owner_id)
	return owner_id, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT user_id, email, role, is_dev, invited_at, invited_by
FROM workspace_members
WHERE workspace_id = $1
ORDER BY invited_at ASC
`

type ListWorkspaceMembersRow struct {
	UserID    string
	Email     string
	Role      string
	IsDev     bool
	InvitedAt time.Time
	InvitedBy string
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID string) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersRow
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Role,
			&i.IsDev,
			&i.InvitedAt,
			&i.InvitedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT workspace_id, name, owner_id, plan, storage_used_bytes, storage_quota_bytes, max_file_size_bytes, max_uploads_per_day, created_at
FROM workspaces
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Name,
			&i.OwnerID,
			&i.Plan,
			&i.StorageUsedBytes,
			&i.StorageQuotaBytes,
			&i.MaxFileSizeBytes,
			&i.MaxUploadsPerDay,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteWorkspaceOwner = `-- name: PromoteWorkspaceOwner :execrows
UPDATE workspace_members
SET role = 'owner'
WHERE workspace_id = $1 AND user_id = $2
`

type PromoteWorkspaceOwnerParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) PromoteWorkspaceOwner(ctx context.Context, arg PromoteWorkspaceOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promoteWorkspaceOwner, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :execrows
UPDATE workspace_members
SET role = $3, is_dev = $4
WHERE workspace_id = $1 AND user_id = $2
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID string
	UserID      string
	Role        string
	IsDev       bool
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkspaceMemberRole,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.IsDev,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspaceOwner = `-- name: UpdateWorkspaceOwner :exec
UPDATE workspaces
SET owner_id = $2
WHERE workspace_id = $1
`

type UpdateWorkspaceOwnerParams struct {
	WorkspaceID string
	OwnerID     string
}

func (q *Queries) UpdateWorkspaceOwner(ctx context.Context, arg UpdateWorkspaceOwnerParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceOwner, arg.WorkspaceID, arg.OwnerID)
	return err
}
