// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const applyBillingEventByAccount = `-- name: ApplyBillingEventByAccount :execrows
UPDATE accounts
SET plan = CASE WHEN $1::text = '' THEN plan ELSE $1::text END,
    storage_quota_bytes = CASE WHEN $1::text = '' THEN storage_quota_bytes ELSE $2::bigint END,
    max_file_size_bytes = CASE WHEN $1::text = '' THEN max_file_size_bytes ELSE $3::bigint END,
    max_uploads_per_5h = CASE WHEN $1::text = '' THEN max_uploads_per_5h ELSE $4::int END,
    max_uploads_per_1week = CASE WHEN $1::text = '' THEN max_uploads_per_1week ELSE $5::int END,
    stripe_customer_id = CASE WHEN $6::text = '' THEN stripe_customer_id ELSE $6::text END,
    stripe_subscription_id = CASE WHEN $7::text = '' AND $1::text <> 'free' THEN stripe_subscription_id ELSE $7::text END,
    billing_status = $8,
    stripe_price_id = $9,
    billing_currency = $10,
    billing_amount_minor = $11,
    billing_interval = $12,
    current_period_end = $13,
    cancel_at_period_end = $14,
    billing_updated_at = $15::timestamptz,
    updated_at = $15::timestamptz
WHERE account_id = $16
`

type ApplyBillingEventByAccountParams struct {
	Plan                 string
	StorageQuotaBytes    int64
	MaxFileSizeBytes     int64
	MaxUploadsPer5h      int32
	MaxUploadsPer1week   int32
	StripeCustomerID     string
	StripeSubscriptionID string
	BillingStatus        string
	StripePriceID        string
	BillingCurrency      string
	BillingAmountMinor   int64
	BillingInterval      string
	CurrentPeriodEnd     sql.NullTime
	CancelAtPeriodEnd    bool
	Now                  time.Time
	AccountID            string
}

// ApplyBillingEvent の account_id 経路。
// 空文字パラメータは既存値を保持する CASE で表現する。
// plan が ” なら plan / quota 関連は据え置き。
// stripe_subscription_id は plan!='free' の場合のみ「空なら据え置き」。
func (q *Queries) ApplyBillingEventByAccount(ctx context.Context, arg ApplyBillingEventByAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyBillingEventByAccount,
		arg.Plan,
		arg.StorageQuotaBytes,
		arg.MaxFileSizeBytes,
		arg.MaxUploadsPer5h,
		arg.MaxUploadsPer1week,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.BillingStatus,
		arg.StripePriceID,
		arg.BillingCurrency,
		arg.BillingAmountMinor,
		arg.BillingInterval,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.Now,
		arg.AccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const applyBillingEventByStripeCustomer = `-- name: ApplyBillingEventByStripeCustomer :execrows
UPDATE accounts
SET plan = CASE WHEN $1::text = '' THEN plan ELSE $1::text END,
    storage_quota_bytes = CASE WHEN $1::text = '' THEN storage_quota_bytes ELSE $2::bigint END,
    max_file_size_bytes = CASE WHEN $1::text = '' THEN max_file_size_bytes ELSE $3::bigint END,
    max_uploads_per_5h = CASE WHEN $1::text = '' THEN max_uploads_per_5h ELSE $4::int END,
    max_uploads_per_1week = CASE WHEN $1::text = '' THEN max_uploads_per_1week ELSE $5::int END,
    stripe_customer_id = CASE WHEN $6::text = '' THEN stripe_customer_id ELSE $6::text END,
    stripe_subscription_id = CASE WHEN $7::text = '' AND $1::text <> 'free' THEN stripe_subscription_id ELSE $7::text END,
    billing_status = $8,
    stripe_price_id = $9,
    billing_currency = $10,
    billing_amount_minor = $11,
    billing_interval = $12,
    current_period_end = $13,
    cancel_at_period_end = $14,
    billing_updated_at = $15::timestamptz,
    updated_at = $15::timestamptz
WHERE stripe_customer_id = $16
`

type ApplyBillingEventByStripeCustomerParams struct {
	Plan                     string
	StorageQuotaBytes        int64
	MaxFileSizeBytes         int64
	MaxUploadsPer5h          int32
	MaxUploadsPer1week       int32
	StripeCustomerIDPassthru string
	StripeSubscriptionID     string
	BillingStatus            string
	StripePriceID            string
	BillingCurrency          string
	BillingAmountMinor       int64
	BillingInterval          string
	CurrentPeriodEnd         sql.NullTime
	CancelAtPeriodEnd        bool
	Now                      time.Time
	StripeCustomerIDMatch    string
}

// ApplyBillingEvent の stripe_customer_id 経路。account_id が未設定の webhook で使う。
func (q *Queries) ApplyBillingEventByStripeCustomer(ctx context.Context, arg ApplyBillingEventByStripeCustomerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyBillingEventByStripeCustomer,
		arg.Plan,
		arg.StorageQuotaBytes,
		arg.MaxFileSizeBytes,
		arg.MaxUploadsPer5h,
		arg.MaxUploadsPer1week,
		arg.StripeCustomerIDPassthru,
		arg.StripeSubscriptionID,
		arg.BillingStatus,
		arg.StripePriceID,
		arg.BillingCurrency,
		arg.BillingAmountMinor,
		arg.BillingInterval,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.Now,
		arg.StripeCustomerIDMatch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const applyBillingPlan = `-- name: ApplyBillingPlan :execrows
UPDATE accounts
SET plan = $1::text,
    storage_quota_bytes = $2::bigint,
    max_file_size_bytes = $3::bigint,
    max_uploads_per_5h = $4::int,
    max_uploads_per_1week = $5::int,
    stripe_customer_id = CASE WHEN $6::text = '' THEN stripe_customer_id ELSE $6::text END,
    stripe_subscription_id = $7::text,
    billing_status = CASE WHEN $1::text = 'free' THEN 'free' ELSE 'active' END,
    billing_updated_at = $8::timestamptz,
    updated_at = $8::timestamptz
WHERE account_id = $9
`

type ApplyBillingPlanParams struct {
	Plan                 string
	StorageQuotaBytes    int64
	MaxFileSizeBytes     int64
	MaxUploadsPer5h      int32
	MaxUploadsPer1week   int32
	StripeCustomerID     string
	StripeSubscriptionID string
	Now                  time.Time
	AccountID            string
}

// plan に応じた quota / 上限を一括で反映する。
// stripe_customer_id は空文字なら既存値を保持 (CASE)。
func (q *Queries) ApplyBillingPlan(ctx context.Context, arg ApplyBillingPlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyBillingPlan,
		arg.Plan,
		arg.StorageQuotaBytes,
		arg.MaxFileSizeBytes,
		arg.MaxUploadsPer5h,
		arg.MaxUploadsPer1week,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Now,
		arg.AccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const applyBillingPlanByStripeCustomerID = `-- name: ApplyBillingPlanByStripeCustomerID :execrows
UPDATE accounts
SET plan = $1::text,
    storage_quota_bytes = $2::bigint,
    max_file_size_bytes = $3::bigint,
    max_uploads_per_5h = $4::int,
    max_uploads_per_1week = $5::int,
    stripe_subscription_id = $6::text,
    billing_status = CASE WHEN $1::text = 'free' THEN 'free' ELSE 'active' END,
    billing_updated_at = $7::timestamptz,
    updated_at = $7::timestamptz
WHERE stripe_customer_id = $8
`

type ApplyBillingPlanByStripeCustomerIDParams struct {
	Plan                 string
	StorageQuotaBytes    int64
	MaxFileSizeBytes     int64
	MaxUploadsPer5h      int32
	MaxUploadsPer1week   int32
	StripeSubscriptionID string
	Now                  time.Time
	StripeCustomerID     string
}

func (q *Queries) ApplyBillingPlanByStripeCustomerID(ctx context.Context, arg ApplyBillingPlanByStripeCustomerIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyBillingPlanByStripeCustomerID,
		arg.Plan,
		arg.StorageQuotaBytes,
		arg.MaxFileSizeBytes,
		arg.MaxUploadsPer5h,
		arg.MaxUploadsPer1week,
		arg.StripeSubscriptionID,
		arg.Now,
		arg.StripeCustomerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deductCredit = `-- name: DeductCredit :exec
INSERT INTO account_credits
  (credit_id, account_id, credit_type, amount_minor, currency, note, granted_by, granted_at)
VALUES ($1, $2, 'consumed', $3, $4, $5, 'system', $6)
`

type DeductCreditParams struct {
	CreditID    string
	AccountID   string
	AmountMinor int64
	Currency    string
	Note        string
	GrantedAt   time.Time
}

// クレジット残高から消費分を差し引く（負の amount_minor を挿入することで残高を減らす）
func (q *Queries) DeductCredit(ctx context.Context, arg DeductCreditParams) error {
	_, err := q.db.ExecContext(ctx, deductCredit,
		arg.CreditID,
		arg.AccountID,
		arg.AmountMinor,
		arg.Currency,
		arg.Note,
		arg.GrantedAt,
	)
	return err
}

const getAccountBudgetForUsage = `-- name: GetAccountBudgetForUsage :one
UPDATE accounts
SET storage_used_bytes = storage_used_bytes
WHERE account_id = $1
RETURNING budget_limit_minor, budget_exceeded
`

type GetAccountBudgetForUsageRow struct {
	BudgetLimitMinor int64
	BudgetExceeded   bool
}

func (q *Queries) GetAccountBudgetForUsage(ctx context.Context, accountID string) (GetAccountBudgetForUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountBudgetForUsage, accountID)
	var i GetAccountBudgetForUsageRow
	err := row.Scan(&i.BudgetLimitMinor, &i.BudgetExceeded)
	return i, err
}

const getCreditBalance = `-- name: GetCreditBalance :one
SELECT COALESCE(SUM(amount_minor), 0)::bigint AS credit_balance_minor
FROM account_credits
WHERE account_id = $1
`

func (q *Queries) GetCreditBalance(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCreditBalance, accountID)
	var credit_balance_minor int64
	err := row.Scan(&credit_balance_minor)
	return credit_balance_minor, err
}

const getModelPricing = `-- name: GetModelPricing :one
SELECT model, input_cost_per_mtoken_minor, output_cost_per_mtoken_minor, currency, display_multiplier
FROM model_pricing
WHERE model = $1
`

type GetModelPricingRow struct {
	Model                    string
	InputCostPerMtokenMinor  int64
	OutputCostPerMtokenMinor int64
	Currency                 string
	DisplayMultiplier        string
}

func (q *Queries) GetModelPricing(ctx context.Context, model string) (GetModelPricingRow, error) {
	row := q.db.QueryRowContext(ctx, getModelPricing, model)
	var i GetModelPricingRow
	err := row.Scan(
		&i.Model,
		&i.InputCostPerMtokenMinor,
		&i.OutputCostPerMtokenMinor,
		&i.Currency,
		&i.DisplayMultiplier,
	)
	return i, err
}

const grantCredit = `-- name: GrantCredit :exec
INSERT INTO account_credits
  (credit_id, account_id, credit_type, amount_minor, currency, note, granted_by, granted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type GrantCreditParams struct {
	CreditID    string
	AccountID   string
	CreditType  string
	AmountMinor int64
	Currency    string
	Note        string
	GrantedBy   string
	GrantedAt   time.Time
}

func (q *Queries) GrantCredit(ctx context.Context, arg GrantCreditParams) error {
	_, err := q.db.ExecContext(ctx, grantCredit,
		arg.CreditID,
		arg.AccountID,
		arg.CreditType,
		arg.AmountMinor,
		arg.Currency,
		arg.Note,
		arg.GrantedBy,
		arg.GrantedAt,
	)
	return err
}

const insertUsageEvent = `-- name: InsertUsageEvent :exec
INSERT INTO usage_events
  (event_id, account_id, workspace_id, job_id, model, input_tokens, output_tokens, cost_minor, currency, created_at,
   paid_via, credit_amount_minor, stripe_amount_minor)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (event_id) DO NOTHING
`

type InsertUsageEventParams struct {
	EventID           string
	AccountID         string
	WorkspaceID       string
	JobID             string
	Model             string
	InputTokens       int64
	OutputTokens      int64
	CostMinor         int64
	Currency          string
	CreatedAt         time.Time
	PaidVia           string
	CreditAmountMinor int64
	StripeAmountMinor int64
}

func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) error {
	_, err := q.db.ExecContext(ctx, insertUsageEvent,
		arg.EventID,
		arg.AccountID,
		arg.WorkspaceID,
		arg.JobID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMinor,
		arg.Currency,
		arg.CreatedAt,
		arg.PaidVia,
		arg.CreditAmountMinor,
		arg.StripeAmountMinor,
	)
	return err
}

const listCreditGrants = `-- name: ListCreditGrants :many
SELECT credit_id, credit_type, amount_minor, currency, note, granted_by, granted_at
FROM account_credits
WHERE account_id = $1
ORDER BY granted_at DESC
LIMIT $2
`

type ListCreditGrantsParams struct {
	AccountID string
	Limit     int32
}

type ListCreditGrantsRow struct {
	CreditID    string
	CreditType  string
	AmountMinor int64
	Currency    string
	Note        string
	GrantedBy   string
	GrantedAt   time.Time
}

func (q *Queries) ListCreditGrants(ctx context.Context, arg ListCreditGrantsParams) ([]ListCreditGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCreditGrants, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreditGrantsRow
	for rows.Next() {
		var i ListCreditGrantsRow
		if err := rows.Scan(
			&i.CreditID,
			&i.CreditType,
			&i.AmountMinor,
			&i.Currency,
			&i.Note,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyUsage = `-- name: ListDailyUsage :many
SELECT usage_date::text, SUM(cost_minor)::bigint AS cost_minor
FROM account_usage_daily
WHERE account_id = $1
  AND ($2::text = '' OR usage_date >= $2::date)
  AND ($3::text = '' OR usage_date <  $3::date)
GROUP BY usage_date
ORDER BY usage_date ASC
`

type ListDailyUsageParams struct {
	AccountID   string
	PeriodStart string
	PeriodEnd   string
}

type ListDailyUsageRow struct {
	UsageDate string
	CostMinor int64
}

func (q *Queries) ListDailyUsage(ctx context.Context, arg ListDailyUsageParams) ([]ListDailyUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyUsage, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyUsageRow
	for rows.Next() {
		var i ListDailyUsageRow
		if err := rows.Scan(&i.UsageDate, &i.CostMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT invoice_id, amount_minor, currency, status,
       hosted_invoice_url, invoice_pdf_url,
       COALESCE(TO_CHAR(period_start AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text AS period_start,
       COALESCE(TO_CHAR(period_end   AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text AS period_end,
       COALESCE(TO_CHAR(paid_at      AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), '')::text AS paid_at,
       TO_CHAR(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS created_at
FROM invoices
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListInvoicesParams struct {
	AccountID string
	Limit     int32
}

type ListInvoicesRow struct {
	InvoiceID        string
	AmountMinor      int64
	Currency         string
	Status           string
	HostedInvoiceUrl string
	InvoicePdfUrl    string
	PeriodStart      string
	PeriodEnd        string
	PaidAt           string
	CreatedAt        string
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesRow
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.HostedInvoiceUrl,
			&i.InvoicePdfUrl,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT payment_method_id, brand, last4, exp_month, exp_year, is_default
FROM payment_methods
WHERE account_id = $1
ORDER BY is_default DESC, created_at DESC
`

type ListPaymentMethodsRow struct {
	PaymentMethodID string
	Brand           string
	Last4           string
	ExpMonth        int32
	ExpYear         int32
	IsDefault       bool
}

func (q *Queries) ListPaymentMethods(ctx context.Context, accountID string) ([]ListPaymentMethodsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentMethods, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentMethodsRow
	for rows.Next() {
		var i ListPaymentMethodsRow
		if err := rows.Scan(
			&i.PaymentMethodID,
			&i.Brand,
			&i.Last4,
			&i.ExpMonth,
			&i.ExpYear,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageByModel = `-- name: ListUsageByModel :many
SELECT model,
       SUM(input_tokens)::bigint  AS input_tokens,
       SUM(output_tokens)::bigint AS output_tokens,
       SUM(cost_minor)::bigint    AS cost_minor,
       COUNT(*)::bigint           AS event_count,
       MAX(currency)::text        AS currency
FROM usage_events
WHERE account_id = $1
  AND ($2::text = '' OR created_at >= $2::timestamptz)
  AND ($3::text = '' OR created_at <  $3::timestamptz)
GROUP BY model
ORDER BY cost_minor DESC
`

type ListUsageByModelParams struct {
	AccountID   string
	PeriodStart string
	PeriodEnd   string
}

type ListUsageByModelRow struct {
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostMinor    int64
	EventCount   int64
	Currency     string
}

func (q *Queries) ListUsageByModel(ctx context.Context, arg ListUsageByModelParams) ([]ListUsageByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsageByModel, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageByModelRow
	for rows.Next() {
		var i ListUsageByModelRow
		if err := rows.Scan(
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMinor,
			&i.EventCount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountBudgetExceeded = `-- name: MarkAccountBudgetExceeded :exec
UPDATE accounts SET budget_exceeded = TRUE WHERE account_id = $1
`

func (q *Queries) MarkAccountBudgetExceeded(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, markAccountBudgetExceeded, accountID)
	return err
}

const markBillingWebhookEventProcessed = `-- name: MarkBillingWebhookEventProcessed :exec
UPDATE billing_events
SET processing_status = $3, error_message = $4, processed_at = $5
WHERE provider = $1 AND event_id = $2
`

type MarkBillingWebhookEventProcessedParams struct {
	Provider         string
	EventID          string
	ProcessingStatus string
	ErrorMessage     string
	ProcessedAt      sql.NullTime
}

func (q *Queries) MarkBillingWebhookEventProcessed(ctx context.Context, arg MarkBillingWebhookEventProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markBillingWebhookEventProcessed,
		arg.Provider,
		arg.EventID,
		arg.ProcessingStatus,
		arg.ErrorMessage,
		arg.ProcessedAt,
	)
	return err
}

const recordBillingWebhookEvent = `-- name: RecordBillingWebhookEvent :execrows
INSERT INTO billing_events (
  provider, event_id, event_type, received_at, processing_status,
  account_id, stripe_customer_id, stripe_subscription_id
) VALUES ($1, $2, $3, $4, 'received', $5, $6, $7)
ON CONFLICT (provider, event_id) DO NOTHING
`

type RecordBillingWebhookEventParams struct {
	Provider             string
	EventID              string
	EventType            string
	ReceivedAt           time.Time
	AccountID            string
	StripeCustomerID     string
	StripeSubscriptionID string
}

// 重複 (provider, event_id) を ON CONFLICT で吸収。
// 戻り値の rows_affected で「新規受信か既受信か」を判定する。
func (q *Queries) RecordBillingWebhookEvent(ctx context.Context, arg RecordBillingWebhookEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordBillingWebhookEvent,
		arg.Provider,
		arg.EventID,
		arg.EventType,
		arg.ReceivedAt,
		arg.AccountID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sumUsageCostByAccount = `-- name: SumUsageCostByAccount :one
SELECT COALESCE(SUM(cost_minor), 0)::bigint
FROM usage_events
WHERE account_id = $1
`

func (q *Queries) SumUsageCostByAccount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumUsageCostByAccount, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAccountBudgetLimit = `-- name: UpdateAccountBudgetLimit :exec
UPDATE accounts
SET budget_limit_minor = $2, budget_exceeded = FALSE, updated_at = $3
WHERE account_id = $1
`

type UpdateAccountBudgetLimitParams struct {
	AccountID        string
	BudgetLimitMinor int64
	UpdatedAt        time.Time
}

func (q *Queries) UpdateAccountBudgetLimit(ctx context.Context, arg UpdateAccountBudgetLimitParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountBudgetLimit, arg.AccountID, arg.BudgetLimitMinor, arg.UpdatedAt)
	return err
}

const upsertAccountUsageDaily = `-- name: UpsertAccountUsageDaily :exec
INSERT INTO account_usage_daily
  (account_id, usage_date, model, input_tokens, output_tokens, cost_minor, event_count, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 1, $7)
ON CONFLICT (account_id, usage_date, model) DO UPDATE SET
  input_tokens = account_usage_daily.input_tokens + EXCLUDED.input_tokens,
  output_tokens = account_usage_daily.output_tokens + EXCLUDED.output_tokens,
  cost_minor = account_usage_daily.cost_minor + EXCLUDED.cost_minor,
  event_count = account_usage_daily.event_count + 1,
  updated_at = EXCLUDED.updated_at
`

type UpsertAccountUsageDailyParams struct {
	AccountID    string
	UsageDate    time.Time
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostMinor    int64
	UpdatedAt    time.Time
}

func (q *Queries) UpsertAccountUsageDaily(ctx context.Context, arg UpsertAccountUsageDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccountUsageDaily,
		arg.AccountID,
		arg.UsageDate,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMinor,
		arg.UpdatedAt,
	)
	return err
}
