// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dynamic_tools.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const incrementDynamicToolUseCount = `-- name: IncrementDynamicToolUseCount :execrows
UPDATE dynamic_tools
SET use_count = use_count + 1
WHERE tool_id = $1
`

func (q *Queries) IncrementDynamicToolUseCount(ctx context.Context, toolID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementDynamicToolUseCount, toolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertDynamicTool = `-- name: InsertDynamicTool :exec
INSERT INTO dynamic_tools (
  tool_id, name, version, scope, origin_workspace_id, origin_job_id,
  description, language, code, io_schema,
  declared_tier, floor_tier, risk_tier, status,
  input_sample, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10,
  $11, $12, $13, $14,
  $15, $16
)
`

type InsertDynamicToolParams struct {
	ToolID            string
	Name              string
	Version           int32
	Scope             string
	OriginWorkspaceID string
	OriginJobID       string
	Description       string
	Language          string
	Code              string
	IoSchema          string
	DeclaredTier      string
	FloorTier         string
	RiskTier          string
	Status            string
	InputSample       string
	CreatedAt         time.Time
}

func (q *Queries) InsertDynamicTool(ctx context.Context, arg InsertDynamicToolParams) error {
	_, err := q.db.ExecContext(ctx, insertDynamicTool,
		arg.ToolID,
		arg.Name,
		arg.Version,
		arg.Scope,
		arg.OriginWorkspaceID,
		arg.OriginJobID,
		arg.Description,
		arg.Language,
		arg.Code,
		arg.IoSchema,
		arg.DeclaredTier,
		arg.FloorTier,
		arg.RiskTier,
		arg.Status,
		arg.InputSample,
		arg.CreatedAt,
	)
	return err
}

const listDynamicToolCandidates = `-- name: ListDynamicToolCandidates :many
SELECT tool_id, name, version, scope, origin_workspace_id, origin_job_id,
       description, language, code, io_schema,
       declared_tier, floor_tier, risk_tier, status,
       input_sample, runtime_version, use_count, created_at, promoted_at, reviewed_by
FROM dynamic_tools
WHERE status = 'candidate'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListDynamicToolCandidates(ctx context.Context, limit int32) ([]DynamicTool, error) {
	rows, err := q.db.QueryContext(ctx, listDynamicToolCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DynamicTool
	for rows.Next() {
		var i DynamicTool
		if err := rows.Scan(
			&i.ToolID,
			&i.Name,
			&i.Version,
			&i.Scope,
			&i.OriginWorkspaceID,
			&i.OriginJobID,
			&i.Description,
			&i.Language,
			&i.Code,
			&i.IoSchema,
			&i.DeclaredTier,
			&i.FloorTier,
			&i.RiskTier,
			&i.Status,
			&i.InputSample,
			&i.RuntimeVersion,
			&i.UseCount,
			&i.CreatedAt,
			&i.PromotedAt,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxDynamicToolVersion = `-- name: MaxDynamicToolVersion :one
SELECT COALESCE(MAX(version), 0)::int AS max_version
FROM dynamic_tools
WHERE scope = $1 AND origin_workspace_id = $2 AND name = $3
`

type MaxDynamicToolVersionParams struct {
	Scope             string
	OriginWorkspaceID string
	Name              string
}

func (q *Queries) MaxDynamicToolVersion(ctx context.Context, arg MaxDynamicToolVersionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, maxDynamicToolVersion, arg.Scope, arg.OriginWorkspaceID, arg.Name)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const promoteDynamicToolCandidate = `-- name: PromoteDynamicToolCandidate :execrows
UPDATE dynamic_tools
SET status = $2, promoted_at = $3
WHERE tool_id = $1
`

type PromoteDynamicToolCandidateParams struct {
	ToolID     string
	Status     string
	PromotedAt sql.NullTime
}

func (q *Queries) PromoteDynamicToolCandidate(ctx context.Context, arg PromoteDynamicToolCandidateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promoteDynamicToolCandidate, arg.ToolID, arg.Status, arg.PromotedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const promoteDynamicToolToGlobal = `-- name: PromoteDynamicToolToGlobal :execrows
UPDATE dynamic_tools
SET scope = 'global', reviewed_by = $2
WHERE tool_id = $1
`

type PromoteDynamicToolToGlobalParams struct {
	ToolID     string
	ReviewedBy string
}

func (q *Queries) PromoteDynamicToolToGlobal(ctx context.Context, arg PromoteDynamicToolToGlobalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promoteDynamicToolToGlobal, arg.ToolID, arg.ReviewedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveActiveDynamicTools = `-- name: ResolveActiveDynamicTools :many
SELECT tool_id, name, version, scope, origin_workspace_id, origin_job_id,
       description, language, code, io_schema,
       declared_tier, floor_tier, risk_tier, status,
       input_sample, runtime_version, use_count, created_at, promoted_at, reviewed_by
FROM dynamic_tools
WHERE status = 'active' AND (scope = 'global' OR origin_workspace_id = $1)
ORDER BY created_at ASC
`

func (q *Queries) ResolveActiveDynamicTools(ctx context.Context, originWorkspaceID string) ([]DynamicTool, error) {
	rows, err := q.db.QueryContext(ctx, resolveActiveDynamicTools, originWorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DynamicTool
	for rows.Next() {
		var i DynamicTool
		if err := rows.Scan(
			&i.ToolID,
			&i.Name,
			&i.Version,
			&i.Scope,
			&i.OriginWorkspaceID,
			&i.OriginJobID,
			&i.Description,
			&i.Language,
			&i.Code,
			&i.IoSchema,
			&i.DeclaredTier,
			&i.FloorTier,
			&i.RiskTier,
			&i.Status,
			&i.InputSample,
			&i.RuntimeVersion,
			&i.UseCount,
			&i.CreatedAt,
			&i.PromotedAt,
			&i.ReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDynamicToolStatus = `-- name: SetDynamicToolStatus :execrows
UPDATE dynamic_tools
SET status = $2
WHERE tool_id = $1
`

type SetDynamicToolStatusParams struct {
	ToolID string
	Status string
}

func (q *Queries) SetDynamicToolStatus(ctx context.Context, arg SetDynamicToolStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDynamicToolStatus, arg.ToolID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
