// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tree.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const countJobMutationsByTarget = `-- name: CountJobMutationsByTarget :one
SELECT COUNT(*)
FROM job_mutation_logs
WHERE job_id = $1 AND target_type = $2
`

type CountJobMutationsByTargetParams struct {
	JobID      string
	TargetType string
}

func (q *Queries) CountJobMutationsByTarget(ctx context.Context, arg CountJobMutationsByTargetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobMutationsByTarget, arg.JobID, arg.TargetType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :exec
INSERT INTO tree_items (id, workspace_id, parent_id, title, level, description, content, override_css, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
`

type CreateItemParams struct {
	ID          string
	WorkspaceID string
	ParentID    sql.NullString
	Title       string
	Level       int32
	Description string
	Content     string
	OverrideCss string
	CreatedBy   string
	CreatedAt   time.Time
}

// Creates a node under an explicit parent. Pass NULL parent_id for a root
// node (sitting directly under the workspace).
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Title,
		arg.Level,
		arg.Description,
		arg.Content,
		arg.OverrideCss,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createStructuredItem = `-- name: CreateStructuredItem :exec
INSERT INTO tree_items (
  id, workspace_id, parent_id, title, level, description, content, override_css,
  created_by, governance_state, last_mutation_job_id, cross_document, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $13)
`

type CreateStructuredItemParams struct {
	ID                string
	WorkspaceID       string
	ParentID          sql.NullString
	Title             string
	Level             int32
	Description       string
	Content           string
	OverrideCss       string
	CreatedBy         string
	GovernanceState   string
	LastMutationJobID string
	CrossDocument     bool
	CreatedAt         time.Time
}

// Creates a node with full governance/mutation metadata. parent_id NULL =
// root node directly under the workspace.
func (q *Queries) CreateStructuredItem(ctx context.Context, arg CreateStructuredItemParams) error {
	_, err := q.db.ExecContext(ctx, createStructuredItem,
		arg.ID,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Title,
		arg.Level,
		arg.Description,
		arg.Content,
		arg.OverrideCss,
		arg.CreatedBy,
		arg.GovernanceState,
		arg.LastMutationJobID,
		arg.CrossDocument,
		arg.CreatedAt,
	)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, workspace_id, parent_id, title, level, description, content, override_css, created_by,
       governance_state, cross_document, created_at
FROM tree_items
WHERE id = $1
`

type GetItemRow struct {
	ID              string
	WorkspaceID     string
	ParentID        sql.NullString
	Title           string
	Level           int32
	Description     string
	Content         string
	OverrideCss     string
	CreatedBy       string
	GovernanceState string
	CrossDocument   bool
	CreatedAt       time.Time
}

func (q *Queries) GetItem(ctx context.Context, id string) (GetItemRow, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i GetItemRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Title,
		&i.Level,
		&i.Description,
		&i.Content,
		&i.OverrideCss,
		&i.CreatedBy,
		&i.GovernanceState,
		&i.CrossDocument,
		&i.CreatedAt,
	)
	return i, err
}

const getItemSummaryUpdateContext = `-- name: GetItemSummaryUpdateContext :one
SELECT workspace_id, content, governance_state
FROM tree_items
WHERE id = $1
`

type GetItemSummaryUpdateContextRow struct {
	WorkspaceID     string
	Content         string
	GovernanceState string
}

func (q *Queries) GetItemSummaryUpdateContext(ctx context.Context, id string) (GetItemSummaryUpdateContextRow, error) {
	row := q.db.QueryRowContext(ctx, getItemSummaryUpdateContext, id)
	var i GetItemSummaryUpdateContextRow
	err := row.Scan(&i.WorkspaceID, &i.Content, &i.GovernanceState)
	return i, err
}

const insertJobMutationLog = `-- name: InsertJobMutationLog :exec
INSERT INTO job_mutation_logs (
  mutation_id, job_id, plan_id, capability_id, workspace_id, target_type, target_id, mutation_type,
  risk_tier, before_json, after_json, provenance_json, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertJobMutationLogParams struct {
	MutationID     string
	JobID          string
	PlanID         string
	CapabilityID   string
	WorkspaceID    string
	TargetType     string
	TargetID       string
	MutationType   string
	RiskTier       string
	BeforeJson     string
	AfterJson      string
	ProvenanceJson string
	CreatedAt      time.Time
}

func (q *Queries) InsertJobMutationLog(ctx context.Context, arg InsertJobMutationLogParams) error {
	_, err := q.db.ExecContext(ctx, insertJobMutationLog,
		arg.MutationID,
		arg.JobID,
		arg.PlanID,
		arg.CapabilityID,
		arg.WorkspaceID,
		arg.TargetType,
		arg.TargetID,
		arg.MutationType,
		arg.RiskTier,
		arg.BeforeJson,
		arg.AfterJson,
		arg.ProvenanceJson,
		arg.CreatedAt,
	)
	return err
}

const listChildIDsByWorkspace = `-- name: ListChildIDsByWorkspace :many
SELECT parent_id, id
FROM tree_items
WHERE workspace_id = $1 AND parent_id IS NOT NULL
ORDER BY created_at ASC, id ASC
`

type ListChildIDsByWorkspaceRow struct {
	ParentID sql.NullString
	ID       string
}

// Every parent-to-child edge in a workspace, in one round trip, used to fill in
// each item's ChildIDs after a tree listing. Doing it per item meant 1+N
// queries, and each of those selected the full row including `content` — so
// assembling a list of ids re-read every node body a second time. At 5,000
// nodes that was 43 ms of query time (against 7 ms for the listing itself) and
// 11 MiB of body text read for nothing. Measurements in
// docs/improvements/client-item-load-testing.md.
//
// Only the two id columns are selected, so the result stays small however large
// the bodies are. Workspace-scoped rather than parent-scoped because a scalar
// parameter needs no array support from the driver.
//
// Ordered by created_at to match the order the item listings use, with id
// breaking ties: a job persists a tree in one statement, so siblings routinely
// share a created_at and that column alone is not a total order. The per-parent
// query had no ORDER BY at all, so sibling order was whatever the scan produced.
func (q *Queries) ListChildIDsByWorkspace(ctx context.Context, workspaceID string) ([]ListChildIDsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listChildIDsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildIDsByWorkspaceRow
	for rows.Next() {
		var i ListChildIDsByWorkspaceRow
		if err := rows.Scan(&i.ParentID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildItems = `-- name: ListChildItems :many
SELECT id, workspace_id, parent_id, title, level, description, content, override_css, created_by,
  governance_state, cross_document, created_at,
  EXISTS(SELECT 1 FROM tree_items child WHERE child.parent_id = tree_items.id) AS has_children
FROM tree_items
WHERE tree_items.parent_id = $1
`

type ListChildItemsRow struct {
	ID              string
	WorkspaceID     string
	ParentID        sql.NullString
	Title           string
	Level           int32
	Description     string
	Content         string
	OverrideCss     string
	CreatedBy       string
	GovernanceState string
	CrossDocument   bool
	CreatedAt       time.Time
	HasChildren     bool
}

func (q *Queries) ListChildItems(ctx context.Context, parentID sql.NullString) ([]ListChildItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChildItems, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildItemsRow
	for rows.Next() {
		var i ListChildItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Title,
			&i.Level,
			&i.Description,
			&i.Content,
			&i.OverrideCss,
			&i.CreatedBy,
			&i.GovernanceState,
			&i.CrossDocument,
			&i.CreatedAt,
			&i.HasChildren,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSourceRefs = `-- name: ListItemSourceRefs :many
SELECT source_ref_id, item_id, source_type, url, repo, ref, path, line_start, line_end,
       kind, external_id, title, COALESCE(confidence, 0) AS confidence,
       snapshot_ref, content_hash, metadata_json, created_at, updated_at
FROM item_source_refs
WHERE item_id = $1
ORDER BY created_at ASC
`

type ListItemSourceRefsRow struct {
	SourceRefID  string
	ItemID       string
	SourceType   string
	Url          string
	Repo         string
	Ref          string
	Path         string
	LineStart    sql.NullInt32
	LineEnd      sql.NullInt32
	Kind         string
	ExternalID   string
	Title        string
	Confidence   float64
	SnapshotRef  string
	ContentHash  string
	MetadataJson string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListItemSourceRefs(ctx context.Context, itemID string) ([]ListItemSourceRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemSourceRefs, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemSourceRefsRow
	for rows.Next() {
		var i ListItemSourceRefsRow
		if err := rows.Scan(
			&i.SourceRefID,
			&i.ItemID,
			&i.SourceType,
			&i.Url,
			&i.Repo,
			&i.Ref,
			&i.Path,
			&i.LineStart,
			&i.LineEnd,
			&i.Kind,
			&i.ExternalID,
			&i.Title,
			&i.Confidence,
			&i.SnapshotRef,
			&i.ContentHash,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSources = `-- name: ListItemSources :many
SELECT s.item_id, s.document_id, s.file_id, f.path AS sub_path, s.chunk_id, s.source_text, COALESCE(s.confidence, 0) AS confidence
FROM item_sources s
LEFT JOIN document_files f ON f.file_id = s.file_id
WHERE s.item_id = $1
`

type ListItemSourcesRow struct {
	ItemID     string
	DocumentID string
	FileID     string
	SubPath    sql.NullString
	ChunkID    string
	SourceText string
	Confidence float64
}

func (q *Queries) ListItemSources(ctx context.Context, itemID string) ([]ListItemSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemSources, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemSourcesRow
	for rows.Next() {
		var i ListItemSourcesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.DocumentID,
			&i.FileID,
			&i.SubPath,
			&i.ChunkID,
			&i.SourceText,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByWorkspace = `-- name: ListItemsByWorkspace :many
SELECT id, workspace_id, parent_id, title, level, description, content, override_css, created_by,
       governance_state, cross_document, created_at
FROM tree_items
WHERE workspace_id = $1
ORDER BY created_at ASC
`

type ListItemsByWorkspaceRow struct {
	ID              string
	WorkspaceID     string
	ParentID        sql.NullString
	Title           string
	Level           int32
	Description     string
	Content         string
	OverrideCss     string
	CreatedBy       string
	GovernanceState string
	CrossDocument   bool
	CreatedAt       time.Time
}

func (q *Queries) ListItemsByWorkspace(ctx context.Context, workspaceID string) ([]ListItemsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByWorkspaceRow
	for rows.Next() {
		var i ListItemsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Title,
			&i.Level,
			&i.Description,
			&i.Content,
			&i.OverrideCss,
			&i.CreatedBy,
			&i.GovernanceState,
			&i.CrossDocument,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootItemsByWorkspace = `-- name: ListRootItemsByWorkspace :many
SELECT id, workspace_id, parent_id, title, level, description, content, override_css, created_by,
       governance_state, cross_document, created_at
FROM tree_items
WHERE workspace_id = $1 AND parent_id IS NULL
ORDER BY created_at ASC
`

type ListRootItemsByWorkspaceRow struct {
	ID              string
	WorkspaceID     string
	ParentID        sql.NullString
	Title           string
	Level           int32
	Description     string
	Content         string
	OverrideCss     string
	CreatedBy       string
	GovernanceState string
	CrossDocument   bool
	CreatedAt       time.Time
}

// Root nodes of the workspace tree: the items sitting directly under the
// workspace (parent_id IS NULL). Replaces the old workspace_root lookup.
func (q *Queries) ListRootItemsByWorkspace(ctx context.Context, workspaceID string) ([]ListRootItemsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listRootItemsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRootItemsByWorkspaceRow
	for rows.Next() {
		var i ListRootItemsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Title,
			&i.Level,
			&i.Description,
			&i.Content,
			&i.OverrideCss,
			&i.CreatedBy,
			&i.GovernanceState,
			&i.CrossDocument,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemForMerge = `-- name: UpdateItemForMerge :execrows
UPDATE tree_items
SET title = $2, description = $3, content = $4, cross_document = TRUE,
    last_mutation_job_id = $5, updated_at = $6
WHERE id = $1
`

type UpdateItemForMergeParams struct {
	ID                string
	Title             string
	Description       string
	Content           string
	LastMutationJobID string
	UpdatedAt         time.Time
}

// Merge a document's knowledge into an existing node: the worker rewrites the
// node's title/description/content and marks it cross_document. item_sources
// gains the new document's provenance via UpsertItemSource.
func (q *Queries) UpdateItemForMerge(ctx context.Context, arg UpdateItemForMergeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateItemForMerge,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.LastMutationJobID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateItemParent = `-- name: UpdateItemParent :exec
UPDATE tree_items
SET parent_id = $2, updated_at = $3
WHERE id = $1
`

type UpdateItemParentParams struct {
	ID        string
	ParentID  sql.NullString
	UpdatedAt time.Time
}

func (q *Queries) UpdateItemParent(ctx context.Context, arg UpdateItemParentParams) error {
	_, err := q.db.ExecContext(ctx, updateItemParent, arg.ID, arg.ParentID, arg.UpdatedAt)
	return err
}

const updateItemSummaryAndMutation = `-- name: UpdateItemSummaryAndMutation :execrows
UPDATE tree_items
SET content = $2, last_mutation_job_id = $3, updated_at = $4
WHERE id = $1
`

type UpdateItemSummaryAndMutationParams struct {
	ID                string
	Content           string
	LastMutationJobID string
	UpdatedAt         time.Time
}

func (q *Queries) UpdateItemSummaryAndMutation(ctx context.Context, arg UpdateItemSummaryAndMutationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateItemSummaryAndMutation,
		arg.ID,
		arg.Content,
		arg.LastMutationJobID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTreeTimestamp = `-- name: UpdateTreeTimestamp :exec
UPDATE tree_items
SET updated_at = $2
WHERE workspace_id = (SELECT workspace_id FROM tree_items WHERE tree_items.id = $1 LIMIT 1)
`

type UpdateTreeTimestampParams struct {
	ID        string
	UpdatedAt time.Time
}

func (q *Queries) UpdateTreeTimestamp(ctx context.Context, arg UpdateTreeTimestampParams) error {
	_, err := q.db.ExecContext(ctx, updateTreeTimestamp, arg.ID, arg.UpdatedAt)
	return err
}

const upsertApprovedAlias = `-- name: UpsertApprovedAlias :exec
INSERT INTO item_aliases (workspace_id, canonical_item_id, alias_item_id, status, updated_at)
VALUES ($1, $2, $3, 'approved', $4)
ON CONFLICT (workspace_id, canonical_item_id, alias_item_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = EXCLUDED.updated_at
`

type UpsertApprovedAliasParams struct {
	WorkspaceID     string
	CanonicalItemID string
	AliasItemID     string
	UpdatedAt       time.Time
}

func (q *Queries) UpsertApprovedAlias(ctx context.Context, arg UpsertApprovedAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertApprovedAlias,
		arg.WorkspaceID,
		arg.CanonicalItemID,
		arg.AliasItemID,
		arg.UpdatedAt,
	)
	return err
}

const upsertItemSource = `-- name: UpsertItemSource :exec
INSERT INTO item_sources (item_id, document_id, file_id, chunk_id, source_text, confidence)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (item_id, document_id, chunk_id)
DO UPDATE SET file_id = EXCLUDED.file_id, source_text = EXCLUDED.source_text, confidence = EXCLUDED.confidence
`

type UpsertItemSourceParams struct {
	ItemID     string
	DocumentID string
	FileID     string
	ChunkID    string
	SourceText string
	Confidence sql.NullFloat64
}

func (q *Queries) UpsertItemSource(ctx context.Context, arg UpsertItemSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertItemSource,
		arg.ItemID,
		arg.DocumentID,
		arg.FileID,
		arg.ChunkID,
		arg.SourceText,
		arg.Confidence,
	)
	return err
}

const upsertItemSourceRef = `-- name: UpsertItemSourceRef :exec
INSERT INTO item_source_refs (
  source_ref_id, item_id, source_type, url, repo, ref, path, line_start, line_end,
  kind, external_id, title, confidence, snapshot_ref, content_hash, metadata_json,
  created_at, updated_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9,
  $10, $11, $12, $13, $14, $15, $16,
  $17, $17
)
ON CONFLICT (source_ref_id)
DO UPDATE SET
  item_id = EXCLUDED.item_id,
  source_type = EXCLUDED.source_type,
  url = EXCLUDED.url,
  repo = EXCLUDED.repo,
  ref = EXCLUDED.ref,
  path = EXCLUDED.path,
  line_start = EXCLUDED.line_start,
  line_end = EXCLUDED.line_end,
  kind = EXCLUDED.kind,
  external_id = EXCLUDED.external_id,
  title = EXCLUDED.title,
  confidence = EXCLUDED.confidence,
  snapshot_ref = EXCLUDED.snapshot_ref,
  content_hash = EXCLUDED.content_hash,
  metadata_json = EXCLUDED.metadata_json,
  updated_at = EXCLUDED.updated_at
`

type UpsertItemSourceRefParams struct {
	SourceRefID  string
	ItemID       string
	SourceType   string
	Url          string
	Repo         string
	Ref          string
	Path         string
	LineStart    sql.NullInt32
	LineEnd      sql.NullInt32
	Kind         string
	ExternalID   string
	Title        string
	Confidence   sql.NullFloat64
	SnapshotRef  string
	ContentHash  string
	MetadataJson string
	CreatedAt    time.Time
}

func (q *Queries) UpsertItemSourceRef(ctx context.Context, arg UpsertItemSourceRefParams) error {
	_, err := q.db.ExecContext(ctx, upsertItemSourceRef,
		arg.SourceRefID,
		arg.ItemID,
		arg.SourceType,
		arg.Url,
		arg.Repo,
		arg.Ref,
		arg.Path,
		arg.LineStart,
		arg.LineEnd,
		arg.Kind,
		arg.ExternalID,
		arg.Title,
		arg.Confidence,
		arg.SnapshotRef,
		arg.ContentHash,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	return err
}

const upsertRejectedAlias = `-- name: UpsertRejectedAlias :exec
INSERT INTO item_aliases (workspace_id, canonical_item_id, alias_item_id, status, updated_at)
VALUES ($1, $2, $3, 'rejected', $4)
ON CONFLICT (workspace_id, canonical_item_id, alias_item_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = EXCLUDED.updated_at
`

type UpsertRejectedAliasParams struct {
	WorkspaceID     string
	CanonicalItemID string
	AliasItemID     string
	UpdatedAt       time.Time
}

func (q *Queries) UpsertRejectedAlias(ctx context.Context, arg UpsertRejectedAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertRejectedAlias,
		arg.WorkspaceID,
		arg.CanonicalItemID,
		arg.AliasItemID,
		arg.UpdatedAt,
	)
	return err
}
