// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"time"
)

const getUser = `-- name: GetUser :one
SELECT user_id, email, display_name, created_at, last_login_at, updated_at
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserWorkspaces = `-- name: ListUserWorkspaces :many
SELECT w.workspace_id, w.name, w.created_at
FROM workspaces w
JOIN account_users au ON au.account_id = w.account_id
WHERE au.user_id = $1 AND w.deleted_at IS NULL
ORDER BY w.created_at DESC
`

type ListUserWorkspacesRow struct {
	WorkspaceID string
	Name        string
	CreatedAt   time.Time
}

func (q *Queries) ListUserWorkspaces(ctx context.Context, userID string) ([]ListUserWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserWorkspacesRow
	for rows.Next() {
		var i ListUserWorkspacesRow
		if err := rows.Scan(&i.WorkspaceID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (user_id, email, display_name, created_at, last_login_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
  email = EXCLUDED.email,
  display_name = EXCLUDED.display_name,
  last_login_at = EXCLUDED.last_login_at,
  updated_at = EXCLUDED.updated_at
RETURNING user_id, email, display_name, created_at, last_login_at, updated_at
`

type UpsertUserParams struct {
	UserID      string
	Email       string
	DisplayName string
	CreatedAt   time.Time
	LastLoginAt time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.UserID,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
		arg.LastLoginAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.UpdatedAt,
	)
	return i, err
}
