// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_chat.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countWorkspaceChatMessagesByRole = `-- name: CountWorkspaceChatMessagesByRole :one
SELECT COUNT(*)::bigint AS message_count
FROM workspace_chat_messages
WHERE conversation_id = $1 AND role = $2
`

type CountWorkspaceChatMessagesByRoleParams struct {
	ConversationID string
	Role           string
}

func (q *Queries) CountWorkspaceChatMessagesByRole(ctx context.Context, arg CountWorkspaceChatMessagesByRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaceChatMessagesByRole, arg.ConversationID, arg.Role)
	var message_count int64
	err := row.Scan(&message_count)
	return message_count, err
}

const countWorkspaceChatSourceDocuments = `-- name: CountWorkspaceChatSourceDocuments :one
SELECT COUNT(DISTINCT d.document_id)::bigint AS document_count
FROM documents d
WHERE d.workspace_id = $1
  AND EXISTS (
    SELECT 1 FROM document_processing_jobs j
    WHERE j.document_id = d.document_id AND j.status = 'succeeded'
  )
`

// CountWorkspaceChatSourceDocuments reports whether the workspace has anything
// answerable at all, so the API can return chat_source_unavailable before it
// spends a model call.
func (q *Queries) CountWorkspaceChatSourceDocuments(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaceChatSourceDocuments, workspaceID)
	var document_count int64
	err := row.Scan(&document_count)
	return document_count, err
}

const createWorkspaceChatConversation = `-- name: CreateWorkspaceChatConversation :one
INSERT INTO workspace_chat_conversations (conversation_id, workspace_id, created_by, title, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING conversation_id, workspace_id, created_by, title, created_at, updated_at
`

type CreateWorkspaceChatConversationParams struct {
	ConversationID string
	WorkspaceID    string
	CreatedBy      string
	Title          string
	CreatedAt      time.Time
}

func (q *Queries) CreateWorkspaceChatConversation(ctx context.Context, arg CreateWorkspaceChatConversationParams) (WorkspaceChatConversation, error) {
	row := q.db.QueryRowContext(ctx, createWorkspaceChatConversation,
		arg.ConversationID,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.Title,
		arg.CreatedAt,
	)
	var i WorkspaceChatConversation
	err := row.Scan(
		&i.ConversationID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceChatMessage = `-- name: CreateWorkspaceChatMessage :one
INSERT INTO workspace_chat_messages (
  message_id, conversation_id, role, content, model_selection, status, error_code, retrieval_snapshot_json, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING message_id, conversation_id, role, content, model_selection, status, error_code, created_at
`

type CreateWorkspaceChatMessageParams struct {
	MessageID             string
	ConversationID        string
	Role                  string
	Content               string
	ModelSelection        string
	Status                string
	ErrorCode             string
	RetrievalSnapshotJson json.RawMessage
	CreatedAt             time.Time
}

type CreateWorkspaceChatMessageRow struct {
	MessageID      string
	ConversationID string
	Role           string
	Content        string
	ModelSelection string
	Status         string
	ErrorCode      string
	CreatedAt      time.Time
}

func (q *Queries) CreateWorkspaceChatMessage(ctx context.Context, arg CreateWorkspaceChatMessageParams) (CreateWorkspaceChatMessageRow, error) {
	row := q.db.QueryRowContext(ctx, createWorkspaceChatMessage,
		arg.MessageID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.ModelSelection,
		arg.Status,
		arg.ErrorCode,
		arg.RetrievalSnapshotJson,
		arg.CreatedAt,
	)
	var i CreateWorkspaceChatMessageRow
	err := row.Scan(
		&i.MessageID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.ModelSelection,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspaceChatMessageSource = `-- name: CreateWorkspaceChatMessageSource :exec
INSERT INTO workspace_chat_message_sources (message_id, ordinal, document_id, chunk_id, item_id, label)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWorkspaceChatMessageSourceParams struct {
	MessageID  string
	Ordinal    int32
	DocumentID string
	ChunkID    string
	ItemID     string
	Label      string
}

func (q *Queries) CreateWorkspaceChatMessageSource(ctx context.Context, arg CreateWorkspaceChatMessageSourceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspaceChatMessageSource,
		arg.MessageID,
		arg.Ordinal,
		arg.DocumentID,
		arg.ChunkID,
		arg.ItemID,
		arg.Label,
	)
	return err
}

const getWorkspaceChatConversation = `-- name: GetWorkspaceChatConversation :one
SELECT conversation_id, workspace_id, created_by, title, created_at, updated_at
FROM workspace_chat_conversations
WHERE conversation_id = $1
`

func (q *Queries) GetWorkspaceChatConversation(ctx context.Context, conversationID string) (WorkspaceChatConversation, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceChatConversation, conversationID)
	var i WorkspaceChatConversation
	err := row.Scan(
		&i.ConversationID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentWorkspaceChatMessages = `-- name: ListRecentWorkspaceChatMessages :many
SELECT message_id, conversation_id, role, content, model_selection, status, error_code, created_at
FROM workspace_chat_messages
WHERE conversation_id = $1 AND status = 'complete'
ORDER BY created_at DESC, message_id DESC
LIMIT $2
`

type ListRecentWorkspaceChatMessagesParams struct {
	ConversationID string
	Limit          int32
}

type ListRecentWorkspaceChatMessagesRow struct {
	MessageID      string
	ConversationID string
	Role           string
	Content        string
	ModelSelection string
	Status         string
	ErrorCode      string
	CreatedAt      time.Time
}

// ListRecentWorkspaceChatMessages returns the newest N messages for prompt history.
// Caller reverses the slice to get chronological order.
func (q *Queries) ListRecentWorkspaceChatMessages(ctx context.Context, arg ListRecentWorkspaceChatMessagesParams) ([]ListRecentWorkspaceChatMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentWorkspaceChatMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentWorkspaceChatMessagesRow
	for rows.Next() {
		var i ListRecentWorkspaceChatMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ModelSelection,
			&i.Status,
			&i.ErrorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceChatConversations = `-- name: ListWorkspaceChatConversations :many
SELECT conversation_id, workspace_id, created_by, title, created_at, updated_at
FROM workspace_chat_conversations
WHERE workspace_id = $1
ORDER BY updated_at DESC
LIMIT $2
`

type ListWorkspaceChatConversationsParams struct {
	WorkspaceID string
	Limit       int32
}

func (q *Queries) ListWorkspaceChatConversations(ctx context.Context, arg ListWorkspaceChatConversationsParams) ([]WorkspaceChatConversation, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceChatConversations, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceChatConversation
	for rows.Next() {
		var i WorkspaceChatConversation
		if err := rows.Scan(
			&i.ConversationID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceChatMessageSources = `-- name: ListWorkspaceChatMessageSources :many
SELECT s.message_id, s.ordinal, s.document_id, s.chunk_id, s.item_id, s.label
FROM workspace_chat_message_sources s
INNER JOIN workspace_chat_messages m ON m.message_id = s.message_id
WHERE m.conversation_id = $1
ORDER BY s.message_id, s.ordinal
`

func (q *Queries) ListWorkspaceChatMessageSources(ctx context.Context, conversationID string) ([]WorkspaceChatMessageSource, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceChatMessageSources, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceChatMessageSource
	for rows.Next() {
		var i WorkspaceChatMessageSource
		if err := rows.Scan(
			&i.MessageID,
			&i.Ordinal,
			&i.DocumentID,
			&i.ChunkID,
			&i.ItemID,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceChatMessages = `-- name: ListWorkspaceChatMessages :many
SELECT message_id, conversation_id, role, content, model_selection, status, error_code, created_at
FROM workspace_chat_messages
WHERE conversation_id = $1
ORDER BY created_at, message_id
LIMIT $2
`

type ListWorkspaceChatMessagesParams struct {
	ConversationID string
	Limit          int32
}

type ListWorkspaceChatMessagesRow struct {
	MessageID      string
	ConversationID string
	Role           string
	Content        string
	ModelSelection string
	Status         string
	ErrorCode      string
	CreatedAt      time.Time
}

func (q *Queries) ListWorkspaceChatMessages(ctx context.Context, arg ListWorkspaceChatMessagesParams) ([]ListWorkspaceChatMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceChatMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceChatMessagesRow
	for rows.Next() {
		var i ListWorkspaceChatMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ModelSelection,
			&i.Status,
			&i.ErrorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceChatSourceChunksLexical = `-- name: ListWorkspaceChatSourceChunksLexical :many
SELECT c.chunk_id, c.document_id, d.filename, f.path AS sub_path, c.heading, c.text, c.source_page,
       (
         SELECT count(*) FROM unnest(string_to_array($1::text, chr(31))) AS t
         WHERE t <> '' AND (c.text ILIKE '%' || t || '%' OR c.heading ILIKE '%' || t || '%')
       )::int AS match_count
FROM document_chunks c
INNER JOIN documents d ON d.document_id = c.document_id
LEFT JOIN document_files f ON f.file_id = c.file_id
WHERE d.workspace_id = $2
  AND EXISTS (
    SELECT 1 FROM document_processing_jobs j
    WHERE j.document_id = d.document_id AND j.status = 'succeeded'
  )
ORDER BY match_count DESC, c.document_id, c.chunk_id
LIMIT $3
`

type ListWorkspaceChatSourceChunksLexicalParams struct {
	Terms       string
	WorkspaceID string
	ResultLimit int32
}

type ListWorkspaceChatSourceChunksLexicalRow struct {
	ChunkID    string
	DocumentID string
	Filename   string
	SubPath    sql.NullString
	Heading    string
	Text       string
	SourcePage sql.NullInt32
	MatchCount int32
}

// ListWorkspaceChatSourceChunksLexical is the deterministic retrieval path used
// while the vector query above is unusable.
//
// It takes a set of terms rather than one string because a single ILIKE of the
// whole question never matches: Japanese questions carry no spaces, so the
// "longest token" is the entire sentence. Scoring by how many terms a chunk
// contains puts the on-topic chunk first and still returns something when no
// term matches, so a miss degrades to a weaker answer rather than no answer.
//
// Terms arrive as one chr(31)-delimited string rather than a text[] because the
// API talks to Postgres through pgx; sqlc renders a []string param as pq.Array,
// which would drag in lib/pq alongside the driver actually in use. The
// delimiter must be chr(31), not '\x1f': with standard_conforming_strings the
// latter is four literal characters, so nothing ever splits and every term
// collapses into one string that matches nothing.
func (q *Queries) ListWorkspaceChatSourceChunksLexical(ctx context.Context, arg ListWorkspaceChatSourceChunksLexicalParams) ([]ListWorkspaceChatSourceChunksLexicalRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceChatSourceChunksLexical, arg.Terms, arg.WorkspaceID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceChatSourceChunksLexicalRow
	for rows.Next() {
		var i ListWorkspaceChatSourceChunksLexicalRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.DocumentID,
			&i.Filename,
			&i.SubPath,
			&i.Heading,
			&i.Text,
			&i.SourcePage,
			&i.MatchCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWorkspaceChatSourceChunks = `-- name: SearchWorkspaceChatSourceChunks :many
SELECT c.chunk_id, c.document_id, d.filename, f.path AS sub_path, c.heading, c.text, c.source_page,
       1 - vector_cosine_distance(c.embedding, $1) AS similarity
FROM document_chunks c
INNER JOIN documents d ON d.document_id = c.document_id
LEFT JOIN document_files f ON f.file_id = c.file_id
WHERE d.workspace_id = $2
  AND c.embedding IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM document_processing_jobs j
    WHERE j.document_id = d.document_id AND j.status = 'succeeded'
  )
ORDER BY vector_cosine_distance(c.embedding, $1)
LIMIT $3
`

type SearchWorkspaceChatSourceChunksParams struct {
	QueryEmbedding interface{}
	WorkspaceID    string
	ResultLimit    int32
}

type SearchWorkspaceChatSourceChunksRow struct {
	ChunkID    string
	DocumentID string
	Filename   string
	SubPath    sql.NullString
	Heading    string
	Text       string
	SourcePage sql.NullInt32
	Similarity int32
}

// SearchWorkspaceChatSourceChunks retrieves candidate chunks for grounding.
// It is scoped by workspace_id, never by chunk id alone, and excludes documents
// with no succeeded processing job (so in-flight uploads cannot be cited).
// The 'succeeded' literal must match jobstatus.LifecycleStateToDB.
//
// NOTE: this requires a pgvector-capable database. The local dev stack runs
// CockroachDB v24.2, which has no vector_cosine_distance, so this query fails
// there — same dormant state as SearchWorkspaceDocumentChunksByVector, which is
// generated but not yet called from Go. Retrieval therefore uses the lexical
// query below as its working path and only reaches for this one where embeddings
// and pgvector are both actually available.
func (q *Queries) SearchWorkspaceChatSourceChunks(ctx context.Context, arg SearchWorkspaceChatSourceChunksParams) ([]SearchWorkspaceChatSourceChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchWorkspaceChatSourceChunks, arg.QueryEmbedding, arg.WorkspaceID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchWorkspaceChatSourceChunksRow
	for rows.Next() {
		var i SearchWorkspaceChatSourceChunksRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.DocumentID,
			&i.Filename,
			&i.SubPath,
			&i.Heading,
			&i.Text,
			&i.SourcePage,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchWorkspaceChatConversation = `-- name: TouchWorkspaceChatConversation :exec
UPDATE workspace_chat_conversations
SET updated_at = $2
WHERE conversation_id = $1
`

type TouchWorkspaceChatConversationParams struct {
	ConversationID string
	UpdatedAt      time.Time
}

func (q *Queries) TouchWorkspaceChatConversation(ctx context.Context, arg TouchWorkspaceChatConversationParams) error {
	_, err := q.db.ExecContext(ctx, touchWorkspaceChatConversation, arg.ConversationID, arg.UpdatedAt)
	return err
}
