# Generated from synthify/localprovider/v1/provider.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .provider_pb2 import CancelGenerationRequest, CancelGenerationResponse, CheckRequest, CheckResponse, GenerateStructuredRequest, GenerateStructuredResponse, GenerateTextRequest, GenerateTextResponse, GetCapabilitiesRequest, GetCapabilitiesResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class LocalProviderService(Protocol):
    async def check(self, request: CheckRequest, ctx: RequestContext[CheckRequest, CheckResponse]) -> CheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_capabilities(self, request: GetCapabilitiesRequest, ctx: RequestContext[GetCapabilitiesRequest, GetCapabilitiesResponse]) -> GetCapabilitiesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def generate_text(self, request: GenerateTextRequest, ctx: RequestContext[GenerateTextRequest, GenerateTextResponse]) -> GenerateTextResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def generate_structured(self, request: GenerateStructuredRequest, ctx: RequestContext[GenerateStructuredRequest, GenerateStructuredResponse]) -> GenerateStructuredResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def cancel_generation(self, request: CancelGenerationRequest, ctx: RequestContext[CancelGenerationRequest, CancelGenerationResponse]) -> CancelGenerationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class LocalProviderServiceASGIApplication(ConnectASGIApplication[LocalProviderService]):
    def __init__(
        self,
        service: LocalProviderService | AsyncGenerator[LocalProviderService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/synthify.localprovider.v1.LocalProviderService/Check": Endpoint.unary(
                    method=MethodInfo(
                        name="Check",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=CheckRequest,
                        output=CheckResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.check,
                ),
                "/synthify.localprovider.v1.LocalProviderService/GetCapabilities": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCapabilities",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=GetCapabilitiesRequest,
                        output=GetCapabilitiesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_capabilities,
                ),
                "/synthify.localprovider.v1.LocalProviderService/GenerateText": Endpoint.unary(
                    method=MethodInfo(
                        name="GenerateText",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=GenerateTextRequest,
                        output=GenerateTextResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.generate_text,
                ),
                "/synthify.localprovider.v1.LocalProviderService/GenerateStructured": Endpoint.unary(
                    method=MethodInfo(
                        name="GenerateStructured",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=GenerateStructuredRequest,
                        output=GenerateStructuredResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.generate_structured,
                ),
                "/synthify.localprovider.v1.LocalProviderService/CancelGeneration": Endpoint.unary(
                    method=MethodInfo(
                        name="CancelGeneration",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=CancelGenerationRequest,
                        output=CancelGenerationResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.cancel_generation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/synthify.localprovider.v1.LocalProviderService"


class LocalProviderServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def check(
        self,
        request: CheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> CheckResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Check",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=CheckRequest,
                output=CheckResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_capabilities(
        self,
        request: GetCapabilitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetCapabilitiesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCapabilities",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=GetCapabilitiesRequest,
                output=GetCapabilitiesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def generate_text(
        self,
        request: GenerateTextRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GenerateTextResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GenerateText",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=GenerateTextRequest,
                output=GenerateTextResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def generate_structured(
        self,
        request: GenerateStructuredRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GenerateStructuredResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GenerateStructured",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=GenerateStructuredRequest,
                output=GenerateStructuredResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def cancel_generation(
        self,
        request: CancelGenerationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CancelGenerationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelGeneration",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=CancelGenerationRequest,
                output=CancelGenerationResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class LocalProviderServiceSync(Protocol):
    def check(self, request: CheckRequest, ctx: RequestContext[CheckRequest, CheckResponse]) -> CheckResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_capabilities(self, request: GetCapabilitiesRequest, ctx: RequestContext[GetCapabilitiesRequest, GetCapabilitiesResponse]) -> GetCapabilitiesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def generate_text(self, request: GenerateTextRequest, ctx: RequestContext[GenerateTextRequest, GenerateTextResponse]) -> GenerateTextResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def generate_structured(self, request: GenerateStructuredRequest, ctx: RequestContext[GenerateStructuredRequest, GenerateStructuredResponse]) -> GenerateStructuredResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def cancel_generation(self, request: CancelGenerationRequest, ctx: RequestContext[CancelGenerationRequest, CancelGenerationResponse]) -> CancelGenerationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class LocalProviderServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: LocalProviderServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/synthify.localprovider.v1.LocalProviderService/Check": EndpointSync.unary(
                    method=MethodInfo(
                        name="Check",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=CheckRequest,
                        output=CheckResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.check,
                ),
                "/synthify.localprovider.v1.LocalProviderService/GetCapabilities": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCapabilities",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=GetCapabilitiesRequest,
                        output=GetCapabilitiesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_capabilities,
                ),
                "/synthify.localprovider.v1.LocalProviderService/GenerateText": EndpointSync.unary(
                    method=MethodInfo(
                        name="GenerateText",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=GenerateTextRequest,
                        output=GenerateTextResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.generate_text,
                ),
                "/synthify.localprovider.v1.LocalProviderService/GenerateStructured": EndpointSync.unary(
                    method=MethodInfo(
                        name="GenerateStructured",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=GenerateStructuredRequest,
                        output=GenerateStructuredResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.generate_structured,
                ),
                "/synthify.localprovider.v1.LocalProviderService/CancelGeneration": EndpointSync.unary(
                    method=MethodInfo(
                        name="CancelGeneration",
                        service_name="synthify.localprovider.v1.LocalProviderService",
                        input=CancelGenerationRequest,
                        output=CancelGenerationResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.cancel_generation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/synthify.localprovider.v1.LocalProviderService"


class LocalProviderServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def check(
        self,
        request: CheckRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> CheckResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Check",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=CheckRequest,
                output=CheckResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_capabilities(
        self,
        request: GetCapabilitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetCapabilitiesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCapabilities",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=GetCapabilitiesRequest,
                output=GetCapabilitiesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def generate_text(
        self,
        request: GenerateTextRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GenerateTextResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GenerateText",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=GenerateTextRequest,
                output=GenerateTextResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def generate_structured(
        self,
        request: GenerateStructuredRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> GenerateStructuredResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GenerateStructured",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=GenerateStructuredRequest,
                output=GenerateStructuredResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def cancel_generation(
        self,
        request: CancelGenerationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CancelGenerationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelGeneration",
                service_name="synthify.localprovider.v1.LocalProviderService",
                input=CancelGenerationRequest,
                output=CancelGenerationResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
