// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	pgvector "github.com/pgvector/pgvector-go"
)

type Account struct {
	AccountID               string
	Name                    string
	Plan                    string
	StorageQuotaBytes       int64
	StorageUsedBytes        int64
	MaxFileSizeBytes        int64
	MaxUploadsPer5h         int32
	MaxUploadsPer1week      int32
	StripeCustomerID        string
	StripeSubscriptionID    string
	BillingStatus           string
	StripePriceID           string
	BillingCurrency         string
	BillingAmountMinor      int64
	BillingInterval         string
	CurrentPeriodEnd        sql.NullTime
	CancelAtPeriodEnd       bool
	BillingUpdatedAt        sql.NullTime
	BudgetLimitMinor        int64
	CurrentPeriodUsageMinor int64
	CurrentPeriodStartedAt  sql.NullTime
	BudgetExceeded          bool
	BudgetAlert80SentAt     sql.NullTime
	BudgetAlert100SentAt    sql.NullTime
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type AccountCredit struct {
	CreditID    string
	AccountID   string
	CreditType  string
	AmountMinor int64
	Currency    string
	Note        string
	GrantedBy   string
	GrantedAt   time.Time
}

type AccountUsageDaily struct {
	AccountID    string
	UsageDate    time.Time
	Model        string
	InputTokens  int64
	OutputTokens int64
	CostMinor    int64
	EventCount   int32
	UpdatedAt    time.Time
}

type AccountUser struct {
	AccountID string
	UserID    string
	Role      string
	JoinedAt  time.Time
}

type BillingEvent struct {
	Provider             string
	EventID              string
	EventType            string
	ReceivedAt           time.Time
	ProcessedAt          sql.NullTime
	ProcessingStatus     string
	ErrorMessage         string
	AccountID            string
	StripeCustomerID     string
	StripeSubscriptionID string
}

type Document struct {
	DocumentID  string
	WorkspaceID string
	UploadedBy  string
	Filename    string
	MimeType    string
	FileSize    int64
	CreatedAt   time.Time
}

type DocumentChunk struct {
	ChunkID    string
	DocumentID string
	FileID     sql.NullString
	Heading    string
	Text       string
	SourcePage sql.NullInt32
	Embedding  pgvector.Vector
}

type DocumentFile struct {
	FileID     string
	DocumentID string
	Path       string
	MimeType   string
	FileSize   int64
	CreatedAt  time.Time
}

type DocumentProcessingJob struct {
	JobID            string
	DocumentID       string
	WorkspaceID      string
	JobType          string
	Status           string
	CurrentStage     string
	ErrorMessage     string
	ParamsJson       string
	RequestedBy      string
	CapabilityID     string
	ExecutionPlanID  string
	PlanStatus       string
	EvaluationStatus string
	RetryCount       int32
	BudgetJson       string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type DynamicTool struct {
	ToolID            string
	Name              string
	Version           int32
	Scope             string
	OriginWorkspaceID string
	OriginJobID       string
	Description       string
	Language          string
	Code              string
	IoSchema          string
	DeclaredTier      string
	FloorTier         string
	RiskTier          string
	Status            string
	InputSample       string
	RuntimeVersion    string
	UseCount          int32
	CreatedAt         time.Time
	PromotedAt        sql.NullTime
	ReviewedBy        string
}

type Invoice struct {
	InvoiceID        string
	AccountID        string
	StripeInvoiceID  string
	AmountMinor      int64
	Currency         string
	Status           string
	HostedInvoiceUrl string
	InvoicePdfUrl    string
	PeriodStart      sql.NullTime
	PeriodEnd        sql.NullTime
	FinalizedAt      sql.NullTime
	PaidAt           sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ItemAlias struct {
	WorkspaceID     string
	CanonicalItemID string
	AliasItemID     string
	Status          string
	UpdatedAt       time.Time
}

type ItemSource struct {
	ItemID     string
	DocumentID string
	FileID     string
	ChunkID    string
	SourceText string
	Confidence sql.NullFloat64
}

type ItemSourceRef struct {
	SourceRefID  string
	ItemID       string
	SourceType   string
	Url          string
	Repo         string
	Ref          string
	Path         string
	LineStart    sql.NullInt32
	LineEnd      sql.NullInt32
	Kind         string
	ExternalID   string
	Title        string
	Confidence   sql.NullFloat64
	SnapshotRef  string
	ContentHash  string
	MetadataJson string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type JobApprovalRequest struct {
	ApprovalID              string
	JobID                   string
	PlanID                  string
	Status                  string
	RequestedOperationsJson string
	Reason                  string
	RiskTier                string
	RequestedBy             string
	ReviewedBy              string
	RequestedAt             time.Time
	ReviewedAt              sql.NullTime
}

type JobCapability struct {
	CapabilityID           string
	JobID                  string
	WorkspaceID            string
	AllowedDocumentIdsJson string
	AllowedItemIdsJson     string
	AllowedOperationsJson  string
	MaxLlmCalls            int32
	MaxToolRuns            int32
	MaxItemCreations       int32
	ExpiresAt              time.Time
	CreatedAt              time.Time
	MaxTransformCreations  int32
	MaxTransformRuns       int32
}

type JobExecutionPlan struct {
	PlanID    string
	JobID     string
	Status    string
	Summary   string
	PlanJson  string
	CreatedBy string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type JobLog struct {
	ID          string
	JobID       string
	WorkspaceID string
	DocumentID  string
	Level       string
	Event       string
	Message     string
	DetailJson  json.RawMessage
	CreatedAt   time.Time
}

type JobMutationLog struct {
	MutationID     string
	JobID          string
	PlanID         string
	CapabilityID   string
	WorkspaceID    string
	TargetType     string
	TargetID       string
	MutationType   string
	RiskTier       string
	BeforeJson     string
	AfterJson      string
	ProvenanceJson string
	CreatedAt      time.Time
}

type JobStageCheckpoint struct {
	JobID     string
	Stage     string
	Status    string
	GcsRef    string
	UpdatedAt time.Time
}

type ModelPricing struct {
	Model                    string
	InputCostPerMtokenMinor  int64
	OutputCostPerMtokenMinor int64
	Currency                 string
	EffectiveFrom            time.Time
	Notes                    string
	DisplayMultiplier        string
}

type PaymentMethod struct {
	PaymentMethodID       string
	AccountID             string
	StripePaymentMethodID string
	Brand                 string
	Last4                 string
	ExpMonth              int32
	ExpYear               int32
	IsDefault             bool
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type TreeItem struct {
	ID                string
	WorkspaceID       string
	ParentID          sql.NullString
	Title             string
	Level             int32
	Description       string
	Content           string
	OverrideCss       string
	CreatedBy         string
	GovernanceState   string
	LastMutationJobID string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CrossDocument     bool
}

type UploadReservation struct {
	ReservationID     string
	AccountID         string
	WorkspaceID       string
	DocumentID        string
	ExpectedSizeBytes int64
	ActualSizeBytes   int64
	Status            string
	ExpiresAt         time.Time
	CreatedAt         time.Time
	ConfirmedAt       sql.NullTime
}

type UsageEvent struct {
	EventID           string
	AccountID         string
	WorkspaceID       string
	JobID             string
	Model             string
	InputTokens       int64
	OutputTokens      int64
	CostMinor         int64
	Currency          string
	CreatedAt         time.Time
	PaidVia           string
	CreditAmountMinor int64
	StripeAmountMinor int64
}

type User struct {
	UserID      string
	Email       string
	DisplayName string
	CreatedAt   time.Time
	LastLoginAt time.Time
	UpdatedAt   time.Time
}

type Workspace struct {
	WorkspaceID string
	AccountID   string
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type WorkspaceChatConversation struct {
	ConversationID string
	WorkspaceID    string
	CreatedBy      string
	Title          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WorkspaceChatMessage struct {
	MessageID             string
	ConversationID        string
	Role                  string
	Content               string
	ModelSelection        string
	Status                string
	ErrorCode             string
	RetrievalSnapshotJson json.RawMessage
	CreatedAt             time.Time
	Grounded              bool
}

type WorkspaceChatMessageSource struct {
	MessageID  string
	Ordinal    int32
	DocumentID sql.NullString
	ChunkID    string
	ItemID     string
	Label      string
}

type WorkspaceMember struct {
	WorkspaceID string
	UserID      string
	Role        string
	InvitedBy   string
	InvitedAt   time.Time
}

type WorkspaceShareLink struct {
	Token       string
	WorkspaceID string
	Role        string
	CreatedBy   string
	ExpiresAt   sql.NullTime
	RevokedAt   sql.NullTime
	CreatedAt   time.Time
}
