// @generated by scripts/generate-firestore-types.mjs
// Source: contracts/firestore/chat-turn.schema.json

export type FirestoreChatTurn = {
  chatId: string;
  turnId: string;
  workspaceId: string;
  paperId: string;
  status: "running" | "succeeded" | "failed";
  content: string;
  commands?: string;
  proposals?: string;
  selectedContextIds?: string[];
  sectionCount?: number;
  finishReason?: "stop" | "max_tokens" | "section_cap" | "safety" | "recitation" | "other";
  reason?: "vertex_model_not_found" | "quota_exceeded" | "agent_error" | "cancelled" | "internal";
  errorMessage: string;
  promptTokens?: number;
  completionTokens?: number;
  createdAt?: string;
  updatedAt: string;
  completedAt?: string;
  expiresAt?: unknown;
};
